### ISSUE TITLE
copy-paste timing

### ISSUE THREAD

**Issue by richlegrand** [paullouisageneau/libdatachannel#1014]
I'm new to webrtc and libdatachannel... I've been playing with the copy-paste example and I have some (dumb) questions. :)

I modified answerer and offerer to wait for all of the ice candidates and then present the sdp description with the candidates (instead of doing a trickle ice connection), and it works fine, but I noticed that if I'm not quick enough with the copying and pasting it fails with DTLS recv: Handshake timeout and handshake failed.  

I noticed that as soon as I copy the offerer's offer into the answerer, the answerer starts trying to initiate a connection.   But I haven't had a chance to copy the answer into the offerer yet.  I'm guessing that since the offerer has no answer it will not connect -- meanwhile the answerer is eliminating candidates and if I'm too slow, it will fail all candidates (?)  This is all just guesses on my part.  

Maybe this is a non-issue if the signalling is reasonably fast, but it got me thinking about gating the process (having the answerer wait until it gets confirmation that the offerer has received the answer), and/or changing timeout values.  Am I making any sense, or am I off in the weeds?

thanks :)

**Comment by paullouisageneau** [comment]
This is expected. As soon as the answering peer has got the remote description and sent the local one, signaling is done for this peer and it proceeds to connection checks. The ICE protocol is designed such as the offerering peer can answer the checks immediately.

Since the network path is direct without any firewall or NAT blocking traffic to the offerer, the answerer peer can establish connectivity and proceed to DTLS handshake. The issue is that the offerer peer needs the remote description to perform connectivity checks on its side (also it would need the fingerprint to check the DTLS certificate anyway), so the answerer waits on DTLS handshake and times out if you are not fast enough.

The is not an issue in real life because signaling is never going to take more than a few seconds. The copy-paste example is only for educational and debugging purposes.

**Comment by fourlastor** [comment]
Is there a way to set a timeout for the connection manually?

I'm hitting the same issue, except I'd like to actually use webrtc without a signaling server (so it will likely take more than a few seconds to be able to exchange information). I looked at the C api docs, but I could find a timeout value only for the websocket server.

**Comment by paullouisageneau** [comment]
@fourlastor There is no way to set the WebRTC connection timeout manually for now. The reason is that the ICE connection establishment is a complex active process which must happen synchronously on both sides, so adjusting the timeout would require extensive modifications of the backoff logic. 

There are multiple timers involved, but the overall timeout should happen after roughly 30s. However, note that the time-critical part is only for setting the answer. The offer can take any duration to be transmitted as the peer connection will not time out waiting for an answer. 

WebRTC is not designed not connect without signaling, so it will always be hacky to rely on the user to forward descriptions.

**Comment by fourlastor** [comment]
Fair enough, however on this point:

> WebRTC is not designed to connect without signaling, so it will always be hacky to rely on the user to forward descriptions.

https://datatracker.ietf.org/doc/html/rfc4566#section-3.3 does mention alternative, non-server based ways to transmit SDP, for example emails.

Could you point me at where I should look for changing this? I might start with a fork, and if I feel I have a solid enough implementation I'd be happy to make a PR with the changes.

**Comment by paullouisageneau** [comment]
> https://datatracker.ietf.org/doc/html/rfc4566#section-3.3 does mention alternative, non-server based ways to transmit SDP, for example emails.

That's right, but those are general considerations for sending SDP, which is a general-purpose format. In the case of WebRTC, you do need to connect synchronously from both sides to achieve NAT and firewall traversal with the Interactive Connectivity Establishment (ICE) protocol (hence "interactive" in the name). If you look at [RFC8445](https://datatracker.ietf.org/doc/html/rfc8445#section-2) which describes ICE:

> ICE assumes that the agents are able to establish a signaling connection between each other.

> Could you point me at where I should look for changing this? I might start with a fork, and if I feel I have a solid enough implementation I'd be happy to make a PR with the changes.

Sure, but this is a bit tricky to get right as there are multiple mechanisms involved. You need at least to modify the [ICE agent backoff logic in libjuice](https://github.com/paullouisageneau/libjuice/blob/0b6f958baba55e1a4eb31ec2137f62b2e07382ae/src/agent.c#L761) to stop exponential backoff at some point and keep sending connectivity checks, then you need to adapt the DTLS timeout in libdatachannel in [impl/dtlstransport.cpp](https://github.com/paullouisageneau/libdatachannel/blob/7841d9f34cf9bd735958ae203a2536c14240c8a5/src/impl/dtlstransport.cpp) (it depends on the crypto library).

**Comment by paullouisageneau** [comment]
> https://datatracker.ietf.org/doc/html/rfc4566#section-3.3 does mention alternative, non-server based ways to transmit SDP, for example emails.

That's right, but those are general considerations for sending SDP, which is a general-purpose format. In the case of WebRTC, you do need to connect synchronously from both sides to achieve NAT and firewall traversal with the Interactive Connectivity Establishment (ICE) protocol (hence "interactive" in the name). If you look at [RFC8445](https://datatracker.ietf.org/doc/html/rfc8445#section-2) which describes ICE:

> ICE assumes that the agents are able to establish a signaling connection between each other.

> Could you point me at where I should look for changing this? I might start with a fork, and if I feel I have a solid enough implementation I'd be happy to make a PR with the changes.

Sure, but this is a bit tricky to get right as there are multiple mechanisms involved. You need at least to modify the [ICE agent backoff logic in libjuice](https://github.com/paullouisageneau/libjuice/blob/0b6f958baba55e1a4eb31ec2137f62b2e07382ae/src/agent.c#L761) to stop exponential backoff at some point and keep sending connectivity checks, then you need to adapt the DTLS timeout in libdatachannel in [impl/dtlstransport.cpp](https://github.com/paullouisageneau/libdatachannel/blob/7841d9f34cf9bd735958ae203a2536c14240c8a5/src/impl/dtlstransport.cpp) (it depends on the crypto library).

An important point though: It is not possible to differentiate a situation were the remote side did not get the answer description and a situation were NAT traversal is impossible. So you need to keep a timeout otherwise it will try to connect indefinitely on NAT traversal failure.

**Comment by paullouisageneau** [comment]
I forgot, you also need to tune the [PAC timer in libjuice](https://github.com/paullouisageneau/libjuice/blob/0b6f958baba55e1a4eb31ec2137f62b2e07382ae/src/agent.h#L41), in addition to changing the retransmission logic.
