### ISSUE TITLE
Rate shaping

### ISSUE THREAD

**Issue by ognkrmms** [paullouisageneau/libdatachannel#1017]
Hi,

I would like to enforce a rate limit to slow down the traffic. I am not sure whether I should try to implement this as a mediahandler.
Where should I begin? Can you point me in the right direction?

Thank you.

**Comment by paullouisageneau** [comment]
This should indeed be done with a `MediaHandler`. However, instead of sending packets synchronously in `outgoing()`, it typically would queue them and send them later in tasks scheduled on the thread pool.

**Comment by ognkrmms** [comment]
I tried implementing this and managed to run it with the streamer example. However, in the real application, I noticed visual artifacts occur even though I am setting a very high bandwidth. I am adding a screenshot below.
I opened a draft PR in our fork in order not to clutter here: https://github.com/vagonhq/libdatachannel/pull/2
Could you check the `Metronome` class and tell me if I am moving in the right direction?
![artifactvideo2](https://github.com/paullouisageneau/libdatachannel/assets/12650228/c3ba1b1e-5972-4c82-8974-eaa074522ee6)

**Comment by paullouisageneau** [comment]
I've had a look at the implementation in https://github.com/vagonhq/libdatachannel/pull/2.

The logic in `BucketPacer` does not make sense to me. I guess the class is supposed to implement a token bucket algorithm, but instead it simply implements logic that resets the budget if called after a second. As a result, the sender will simply consume the whole 300K budget by bursting everything immediately, spin every 5ms uselessly for a while as the budget is 0 until one second is elapsed, then bursting everything again. A proper token bucket should calculate available tokens by adding fill rate multiplied by time elapsed since last call to previously available tokens and cap by the bucket size.

Also, both `Metronome::outgoing` and `Metronome::senderProcess` schedule calls to `senderProcess`, meaning two threads may run the method at the same time, but the access to `mPacerAlgorithm` is not synchronized. The `PacerAlgorithm` interface is prone to race conditions if two threads manipulate the `getBudget` and `setBudget` methods in parallel. The interface for a token bucket should be something like `bool spend(int budget)` that does both checking and removing tokens atomically.

Actually, the token bucket coupled with a constant scheduling duration is a weird choice, and the interface to specify another hypothetical algorithm is not very useful as you can't change the scheduling logic this way. Why not simply calculate the elapsed time since last send in `senderProcess` and multiply it by the pace rate to know the budget? (If you want to be precise, over-budget bytes should also be removed from budget on next call.)
