### ISSUE TITLE
How to check that connection is stucked?

### ISSUE THREAD

**Issue by ufna** [paullouisageneau/libdatachannel#1078]
I'm testing scenario like this:

1. client A connected to B with webrtc, all is ok.
2. client A connects/disconnects to VPN (wireguard).
3. then no data stream between clients, but no errors or close events were triggered.

Is it possible to check that we have no real data transfer for some time?

**Comment by paullouisageneau** [comment]
I guess you are referring to data channels here. Connection loss is detected after a number of failed retransmissions which can be changed with `maxRetransmitAttempts` (default is 5). When no data is transmitted between peers, heartbeats are sent instead of data at a time interval `heartbeatInterval` (default is 10s).

You can shorten the heartbeat interval prior to creating a peer connection:
```cpp
rtc::SctpSettings settings = {};
settings.heartbeatInterval = std::chrono::milliseconds(1000); // 1s
rtc::SetSctpSettings(std::move(settings));
```

**Comment by ufna** [comment]
Got the idea, that's what I was looking for! Thanks!
