### ISSUE TITLE
Issue of RtcpNackResponder incoming()

### ISSUE THREAD

**Issue by zhan6841** [paullouisageneau/libdatachannel#1087]
It seems that the way that **RtcpNackResponder::incoming()** handles NACK packets and retransmission cannot retransmit the lost packets correctly to the receiver. 
```
for (auto sequenceNumber : missingSequenceNumbers) {
	if (auto optPacket = mStorage->get(sequenceNumber))
		send(make_message(*optPacket.value()));
}
```
It will trigger an SRTP error status **srtp_err_status_replay_fail** on the receiver side (which is also implemented w/ libdatachannel), indicating the sequence number of an SSRC does not strictly increase, if I understand it correctly. This happens in **DtlsSrtpTransport::recvMedia()** and a related discussion is here #866 
```
[rtc::impl::DtlsSrtpTransport::recvMedia@178] Incoming SRTP packet is a replay
```

I guess the way to fix it is to warp the retransmitted packets to **RtpRtx** and send them using another SSRC w/ its own sequence number.

**Comment by paullouisageneau** [comment]
> It will trigger an SRTP error status **srtp_err_status_replay_fail** on the receiver side (which is also implemented w/ libdatachannel), indicating the sequence number of an SSRC does not strictly increase, if I understand it correctly. This happens in **DtlsSrtpTransport::recvMedia()** and a related discussion is here #866

libsrtp does not rely on strictly increasing sequence number, as the network might reorder packets. Instead, it maintains a replay window to mark which packets were received. The window size is set to 1024 in libdatachannel: 
https://github.com/paullouisageneau/libdatachannel/blob/b5518ffbd03e53ac2b0ae1ae8b68109694e67a84/src/impl/dtlssrtptransport.cpp#L347

If a retransmitted packet triggers `srtp_err_status_replay_fail` on receiver side, it means the packet was actually received before, so the retransmission was useless and the retransmitted packet can be dropped. This is harmless and can happen under normal operation.

Issue #866 is a different thing, it is about sending (not receiving) with the same SSRC and sequence number going in the past because of a inconsistent RTP flow on user side. It'll typically cause libsrtp to fail with `err_status_replay_old` as the sequence is out of the replay window.

**Comment by zhan6841** [comment]
Thanks for the explanation. I think I figured the real issue out after reading it!
