### ISSUE TITLE
Setting remote description does not trigger generation of local description for peer without data channel. 

### ISSUE THREAD

**Issue by gamedolphin** [paullouisageneau/libdatachannel#117]
When setting the remote description from an offerer, with `int rtcSetRemoteDescription(int pc, const char *sdp, const char *type);` on peer connection, the expected behavior is for the local description callback to be triggered, but that does not happen. I see a log message that says `Fingerprint must be set to generate an SDP string` which might be related.

**Comment by gamedolphin** [comment]
I am attempting to create a unity wrapper for this wonderful library :) I got the websockets to work perfectly. Been stuck with the local description not being generated. :)

**Comment by gamedolphin** [comment]
Nvm, found the problem. It was on the c# side of things. The sdp string was being marshalled into an `LPWStr` which it doesn't need to. Once I removed the marshalling (I added it for all strings, 🤦‍♂️ ) , it works!

**Comment by paullouisageneau** [comment]
OK great!

Don't forget to check the return value of `rtcSetRemoteDescription` like other function, if it's non-zero the call failed. The return value will be `RTC_ERR_INVALID` for an invalid argument or `RTC_ERR_FAILURE` for a runtime error. The log might help, in your case it didn't find any fingerprint in the SDP string because of the marshalling.
