### ISSUE TITLE
Client example confusion

### ISSUE THREAD

**Issue by JadeVand** [paullouisageneau/libdatachannel#1188]
Hi, I'm sorry my C++ knowledge is severely limited to pre C++11 and I"m having a lot of trouble understanding the client example. I'm trying to separate and break down the code to components but it just seems very circular logic to me and I can't wrap my head around it.

From my understanding of the code:
Client A creates an offer (SDP).
Client A creates a datachannel.
Client A sends offer to client B.
Client B receives the offer.
Client B creates a responds using the same function Client A initially used (createPeerConnection).

Where I'm confused is, when Client creates an offer how is it that the type is automatically treated as an "offer". But when client B uses the same function , the type is now an "answer". 

The other area I'm confused about is createPeerConnection has a callback for pc->onDataChannel, in which datachannel object is passed in, then it sets up callbacks for onOpen , onClosed and onMessage. But client A also creates a data channel after createPeerConnection is called, in which it sets up callbacks for onOpen onClosed and onMessage...

I'm sorry I just don't understand this code..

**Comment by paullouisageneau** [comment]
> Where I'm confused is, when Client creates an offer how is it that the type is automatically treated as an "offer". But when client B uses the same function , the type is now an "answer".

The library handles description types automatically. By default, when a local description is set, the description type is determined by the current signaling state: basically, if a new offer was set, it generates an answer for it, otherwise it generates an offer. That's why the same method results in a different type, as the underlying signaling state is different.

The behavior matches the one of the JavaScript WebRTC API in browsers when calling [setLocalDescription() without parameters](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/setLocalDescription#implicit_description) which is [a good practice to keep the signaling code simple](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/setLocalDescription#implicit_descriptions).

> The other area I'm confused about is createPeerConnection has a callback for pc->onDataChannel, in which datachannel object is passed in, then it sets up callbacks for onOpen , onClosed and onMessage. But client A also creates a data channel after createPeerConnection is called, in which it sets up callbacks for onOpen onClosed and onMessage...

The logic mimics [how the JavaScript API in browsers is designed](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/createDataChannel#examples): data channels are created on one side and received on the other. After creation or reception, the data channel is symmetrical and you can set the same callbacks on it. As it happens, the side creating the first data channel becomes the WebRTC offerer.

**Comment by JadeVand** [comment]
Thank you very much for the explanation! I'm beginning to understand it better now.
