### ISSUE TITLE
Multiple stun server & stun server credentials

### ISSUE THREAD

**Issue by murat-dogan** [paullouisageneau/libdatachannel#12]
I was using webrtc datachannel before seeing this library for one of my project.
Now I want to integrate this library instead of giant webrtc datachannel.

I have some questions for now;
*  In webrtc I can use multiple stun server. As I see in this project we have to use only one. What is the difference?
* I could not find any place for stun credentials if needed. (username, password for stun server)

**Comment by paullouisageneau** [comment]
- You are right, when multiple STUN servers are specified, it uses one of the resolvable ones randomly. This behavior is acceptable according to [RFC 8445](https://tools.ietf.org/html/rfc8445#section-5.1.1.2), but it's different from the behavior of browsers implementing WebRTC, which is gathering candidates from all the STUN servers, which allows to address specific topologies with hosts between cascading NATs. Anyway, I don't see how to replicate the behavior of browsers with libnice for now.

- I didn't implement STUN server credentials because as far as I know, STUN servers on the public Internet never have authentication. Credentials are typically for TURN servers, which are not supported.

**Comment by murat-dogan** [comment]
Some firewalls blocks all UDP communication.
I would love to use TCP ports for ICE communication and also for data channel.

Can we enable this option?
```
g_object_set(G_OBJECT(mNiceAgent.get()), "ice-tcp", FALSE, nullptr);
```

I made some tests and it looks OK.

**Comment by paullouisageneau** [comment]
Sure, in that case could you please add an option `enableTcp` (with default false) to do so in `Configuration`?
Also, to do everything cleanly you would need to handle TCP candidates in `Candidate::resolve()` (it should use `SOCK_STREAM` and `IPPROTO_TCP`).

**Comment by paullouisageneau** [comment]
ICE TCP support added in https://github.com/paullouisageneau/libdatachannel/pull/16

**Comment by murat-dogan** [comment]
Also supporting TURN server with #14
