### ISSUE TITLE
Websocket::Open crash

### ISSUE THREAD

**Issue by huangshilinp2p** [paullouisageneau/libdatachannel#1210]
![11111](https://github.com/paullouisageneau/libdatachannel/assets/163392153/04953c7d-6c96-4a85-9673-3807532314f9)

**Comment by huangshilinp2p** [comment]
Can any of you experts give me some ideas?

**Comment by paullouisageneau** [comment]
This seems to be a very specific issue on Windows similar to https://github.com/paullouisageneau/libdatachannel/issues/448

It looks like the standard library the program runs with is different from the one you built libdatachannel with, in a way that crashes instead of failing cleanly. It doesn't seem related to libdatachannel in itself.

**Comment by huangshilinp2p** [comment]
Thank you @paullouisageneau . The problem has been solved. Mainly because the dependent MSVCRT and  UCRT files are incorrect.
