### ISSUE TITLE
Source directory requires read/write filesystem during build

### ISSUE THREAD

**Issue by pschichtel** [paullouisageneau/libdatachannel#1227]
Hi! I'm currently working in Java bindings of libdatachannel for a project of mine. The project will be cross-compiled using dockcross a for a set of architectures. To speed up the build process in these JNI-binding projects I build all target architectures in parallel. To ensure this is safe, I'm mounting the sources as read-only into the dockcross container and only the architecture-specific output directory is mounted read/write.

"Unfortunately" libdatachannel uses cmake's configure_file to render the version.h.in template into the source directory, which breaks the assumption "source directories won't be written during build, only output directories".

I don't have a ton of experience with cmake, but I see 2 general ways around this:

1. instead of having a header file with the 4 defines, the defines could be added using cmake's [add_definitions](https://cmake.org/cmake/help/latest/command/add_definitions.html) (or the newer alternatives)
2. A folder in the output directory could be setup and added to the includes, then the configure_file command could place the output there

I'd be willing to make a PR if either of the options are acceptable or if we come up with another solution that fits better. I'd also be fine if this is not something you want to do.

**Comment by paullouisageneau** [comment]
> 1. instead of having a header file with the 4 defines, the defines could be added using cmake's [add_definitions](https://cmake.org/cmake/help/latest/command/add_definitions.html) (or the newer alternatives)

This is not a solution because definitions won't be written in headers so they won't be there when a program includes them after building and installing.

>  2. A folder in the output directory could be setup and added to the includes, then the configure_file command could place the output there

This is typical for a CMake build but libdatachannel also supports alternative build systems (Makefile and Jamfile), which would be broken due to the missing header.

Generating the version.h header was added by @Sean-Der in https://github.com/paullouisageneau/libdatachannel/pull/1112 only to synchronize the CMake version and the version in header: https://github.com/paullouisageneau/libdatachannel/blob/fb7444dbe574fe54004628ba13920055d2bf643e/CMakeLists.txt#L263
It is only necessary for the workflow checking the version in [check-version.yml](https://github.com/paullouisageneau/libdatachannel/blob/master/.github/workflows/check-version.yml).

I think a simple way to fix your issue is to introduce a CMake option, let's say `RTC_UPDATE_VERSION_HEADER`, defaulting to `OFF`, and condition the version file configuration with it. It would be enabled in check-version.yml with `-DRTC_UPDATE_VERSION_HEADER=1`. What do you think?

**Comment by pschichtel** [comment]
yeah that would also work for me, sure

**Comment by pschichtel** [comment]
@paullouisageneau I submitted https://github.com/paullouisageneau/libdatachannel/pull/1231
