### ISSUE TITLE
Data channels created by createDataChannel in a multithreaded may occasionally lose events

### ISSUE THREAD

**Issue by xicilion** [paullouisageneau/libdatachannel#1246]
When we create a data channel in a multi-threading environment using `createDataChannel` and then register a callback function with `dc->onOpen`, sometimes the `open` event may be triggered before successfully registering `onOpen` because the data channel has already started working. As a result, we may miss the notification of this event.

One possible solution is to add a callback function in `DataChannelInit`, and then call the callback function immediately after successfully creating the channel in `emplaceDataChannel`, before releasing `mDataChannelsMutex`.

**Comment by xicilion** [comment]
It seems that the `DataChannel` in `emplaceDataChannel` is `rtc::impl::DataChannel` and cannot be used directly. If that's the case, it might be necessary to set up a set of initialization callback functions directly in `DataChannelInit` and then set them in `emplaceDataChannel`.

**Comment by paullouisageneau** [comment]
> When we create a data channel in a multi-threading environment using `createDataChannel` and then register a callback function with `dc->onOpen`, sometimes the `open` event may be triggered before successfully registering `onOpen` because the data channel has already started working. As a result, we may miss the notification of this event.

No, you may not miss events as `openCallback` is a `synchronized_stored_callback`: https://github.com/paullouisageneau/libdatachannel/blob/57e06d83789e146e22d155d237afb3cea9a21037/src/impl/channel.hpp#L35

As a result it replays the last missed call:
https://github.com/paullouisageneau/libdatachannel/blob/57e06d83789e146e22d155d237afb3cea9a21037/include/rtc/utils.hpp#L116

This means that if you set the callback after the event, it should trigger the callback immediately. If you miss events, the cause is elsewhere.

**Comment by xicilion** [comment]
Thank you for the explanation, I'll take another look.
