### ISSUE TITLE
DTLS recv: invalid map<K, T> key

### ISSUE THREAD

**Issue by ognkrmms** [paullouisageneau/libdatachannel#1271]
Hi,

I am testing what happens to connection during congestion. I have a tool that limits the bandwidth. When I introduce the bandwidth limit, the connection is interrupted and I see the following logs:
```
rtc::impl::DtlsTransport::doRecv@987: DTLS recv: invalid map<K, T> key
rtc::impl::DtlsTransport::doRecv@991: DTLS closed
rtc::impl::PeerConnection::changeState@1220: Changed state to disconnected
rtc::impl::SctpTransport::incoming@454: SCTP disconnected
```
First, I do not understand the invalid map exception because I could not find any use of a map object. Where does this exception come from? 

Second, If I comment out two lines as shown below, Chrome first changes connection state to disconnected and then to connected and the stream continues.
```C++
if (state() == State::Connected) {
	PLOG_INFO << "DTLS closed";
	//changeState(State::Disconnected);
	//recv(nullptr);
} else {
	PLOG_ERROR << "DTLS handshake failed";
	changeState(State::Failed);
}
```
What is the reason behind sending nullptr to recv there? Because immediately after logs above connection state turns into closed. I think this is breaking the connection without any chance to recover.

**Comment by paullouisageneau** [comment]
> First, I do not understand the invalid map exception because I could not find any use of a map object. Where does this exception come from?

There is indeed no map there. I think the exception could come from user code in the global media handler, because `impl::DtlsSrtpTransport::demuxMessage()` ends up calling `impl::PeerConnection::forwardMedia()` which calls `incoming()` on the global media handler without catching exceptions leaking from it. Is it a possible explanation?

> What is the reason behind sending nullptr to recv there? Because immediately after logs above connection state turns into closed. I think this is breaking the connection without any chance to recover.

Null messages are a signal to indicate end of stream to the upper layer. It is useful to ensure things are properly flushed. Here, it's expected that everything closes down, exceptions caught here are supposed to indicate an unrecoverable error.
