### ISSUE TITLE
DTLS Handshake is really slow with Firefox

### ISSUE THREAD

**Issue by stazio** [paullouisageneau/libdatachannel#155]
Hi @paullouisageneau,
As the title suggests, I am noticing a long delay between the initialization of the DTLS transport, and the completion of the DTLS handshake. It can take upwards of 15 seconds or more to establish said connection (sometimes even timing out). Do you have any idea why this is?
I have also disabled all of my media stuff and tried using master.

**Comment by paullouisageneau** [comment]
Is it with OpenSSL as backend? I think this is linked to the unsolved issue in https://github.com/paullouisageneau/libdatachannel/issues/58

**Comment by stazio** [comment]
It was happening with GNuTLS as well.

**Comment by paullouisageneau** [comment]
OK, I'm looking into it.

**Comment by stazio** [comment]
It is definitely some kind of race condition. I had to refactor a bunch of my code and it stopped happening. So, I guess it's okay now?

**Comment by paullouisageneau** [comment]
The issues seems to appear only when libdatachannel is offering. In that case, libdatachannel takes the controlling ICE role, and even if it selects a working network pair quickly, it seems Firefox waits for a pair to be actually nominated. This can take some time is there is a non-working higher priority-pair because the timeout is pretty long in libjuice. I'll fix it by making the nomination more aggressive.
