### ISSUE TITLE
Infinite loop at Description constructor

### ISSUE THREAD

**Issue by RodrigoSantiago** [paullouisageneau/libdatachannel#170]
In some cases the Description was never added to the PeerConnection. I realized that this method was an infinite loop.
Removing `! line.empty()` seems a fix, even allowed the connection. I couldn't understand why it was used

description.cpp
`while (std::getline(ss, line) || !line.empty()) `

**Comment by paullouisageneau** [comment]
When `std::getline` reaches the end of the description, it sets `eofbit` on `ss`, so the `while` condition will be `false`. Yet, there could be a last line in the description missing a newline character, hence the `!line.empty()` test to check if there is such a last line to process. This works because `std::getline` is supposed to [erase the contents of the string before starting to read](https://en.cppreference.com/w/cpp/string/basic_string/getline), so calling it past the end should result in an empty string.

However, it could be that the standard library you use is not perfectly compliant, so it might need a workaround. What platform is it?

**Comment by RodrigoSantiago** [comment]
Exactly. The last line does not have a newline character. However, this error only occurs on Android (armeabi-v7a, API 21, Target 30)

**Comment by paullouisageneau** [comment]
Could you please try with https://github.com/paullouisageneau/libdatachannel/pull/172?
It should solve the issue.
