### ISSUE TITLE
ICE Internals

### ISSUE THREAD

**Issue by murat-dogan** [paullouisageneau/libdatachannel#20]
Hi @paullouisageneau ,

I am using webrtc since 2 years but I don't know internals so much.
I am trying to learn with this project.

Have some basic questions;
* Is communication with STUN/TURN for gathering candidates encrypted?
* Basically libnice will select a candidate pair and all communication will be over this pair. 
For example; 
```
Candidate 1: a=candidate:9 1 TCP 1010828031 192.168.1.25 60451 typ host tcptype passive
Candidate 2: a=candidate:9 1 TCP 1010828031 192.168.1.25 43948 typ host tcptype passive
```
If this pair is selected, then communication will be over this ports (TCP).
Is this right?
Is this communication is encrypted?
* If above is true then what is ```sctptransport``` for?
I mean all communication is over libnice (TCP) what is the purpose of sctp layer?

Thanks,

**Comment by paullouisageneau** [comment]
Good questions!

- The communication for gathering candidates is not encrypted. It uses an ICE protocol similar to the one to check candidates pairs, which is pretty lightweight.

- You are right, except during candidate trickling, if a better pair is received and succeeds, communication might use the better one instead (that's why the ICE transport has two states "connected" and "completed"). Once ICE is connected, communication is encrypted by DTLS, irrelevant of the lower layer (UDP or TCP). Actually, the ICE layer is abstracted as a datagram transport, even if it is over TCP (in which case ICE uses a framing protocol to mark the datagram boundaries in the TCP stream).

- The SCTP layer is indeed not really suitable over DTLS/TCP, but it has to be here for consistency as TCP is just a fallback to transmit datagrams if UDP is blocked. In any case, you still need a way to multiplex data channels, reassemble messages, and differentiate message types. Basically, the core data channel protocol stack is SCTP/DTLS, then you need anything than can transmit datagrams below.

**Comment by murat-dogan** [comment]
Thanks for answers.

First if you have any reference documentation please share with me.
I googled but most of documents are very basic.

* If we are using a STUN/TURN server which has TSL (```RelayType::TurnTls```) and we are communicating on port 443, Is  gathering candidates still not encrypted?

* As I understood communication layers is like that;
SCTP <-> DTLS <-> ICE(UDP)   
If UDP is blocked than it will be;
SCTP <-> DTLS <-> ICE(TCP)
Is that right?   

* Actually SCTP is not UDP or TCP. It is a different protocol. So it is a little bit confusing.

**Comment by paullouisageneau** [comment]
- STUN can't use TLS, its purpose is only to open a port mapping on the NAT, so it has to be done over UDP, and the only transmitted information is the client address, which is pointless to encrypt. Indeed I forgot about TURN/TLS which is indeed encrypted, but it's mostly a fallback to help firewall traversal (it looks more like an HTTPS connection), it doesn't add security.

- Yes, that's right.

- That's a good point, SCTP was indeed developped to work over IP, just like TCP/IP and UDP/IP. However, since deployment has been a pain (especially because NATs and firewalls support only TCP and UDP), in practice it's mostly used over UDP, or DTLS/UDP here to add security.
