### ISSUE TITLE
Question about time required to run PeerConnection::setLocalDescription

### ISSUE THREAD

**Issue by hanseuljun** [paullouisageneau/libdatachannel#222]
The situation is creating a PeerConnection and calling SetLocalDescription within an AR headset., which has limited computing power and is connected to the Internet via a Wifi router

With the first PeerConnection instance, running SetLocalDescription takes about 30 seconds. After then, creating another instance of PeerConnection and calling SetLocalDescription takes much less than a second.

My questions are:
1. Is this expected behavior?
2. In case this is expected behavior, does this mean the first SetLocalDescription() contains a global initialization of something?
3. If there is a sort of a global initialization, can that be done before the first call of SetLocalDescription, for example, by calling a function within a background thread?

**Comment by paullouisageneau** [comment]
>     1. Is this expected behavior?

Yes it is.

>     2. In case this is expected behavior, does this mean the first SetLocalDescription() contains a global initialization of something?

Your guess is right, the library will lazy-load global resources when they are needed by a `PeerConnection`. Since the device has limited computing power, generating the local TLS certificate may take a long time. Additionally, it seems the certificate generation with OpenSSL on Windows is relatively slow already (this might be worth investigating separately).

Could you please try to lower `bits` to 2048 here to see if it helps? If it does, I could add a compilation flag for it (security will still be good enough). https://github.com/paullouisageneau/libdatachannel/blob/d59c209c2044b74b8a60f1de68aadea28298e6b3/src/certificate.cpp#L193

>     3. If there is a sort of a global initialization, can that be done before the first call of SetLocalDescription, for example, by calling a function within a background thread?

Yes, there is a dedicated global function: `rtc::Preload()`. When called, it blocks until global resources are loaded, in particular until the certificate is generated. You could call it in a background thread before instantiating the first `PeerConnection`.

**Comment by hanseuljun** [comment]
Wow the tweak to 2048 bits really works. The first SetLocalDescription() now takes less than a second! Thank you!!

**Comment by paullouisageneau** [comment]
OK great! Actually, if it woks so well, I think I'll also change the default to 2048.

**Comment by hanseuljun** [comment]
If you were on yelp, I would have given you a five star haha

**Comment by paullouisageneau** [comment]
https://github.com/paullouisageneau/libdatachannel/pull/224 adds an option `RSA_KEY_BITS_2048` that you should enable. It also reduces the default OpenSSL RSA key size to 3072.
