### ISSUE TITLE
WebSocket open url issue

### ISSUE THREAD

**Issue by dbotha** [paullouisageneau/libdatachannel#238]
Hi Paul-Louis,

When I explicitly include the port in the open url i.e. `"wss://example.com:443"` the connection fails to open. However `"wss://example.com"` will work. 

It appears that the problem is with these lines (and `mHost` being set differently in both cases):

https://github.com/paullouisageneau/libdatachannel/blob/de47fec19bbc4d965fdc9933c7dfd7db7079bb80/src/websocket.cpp#L77-L82

Changing them to the following seems to do the trick for me:
```
if (mService.empty()) {
    mService = mScheme == "ws" ? "80" : "443";
}
mHost = mHostname;
```

Or am I doing something wrong?

Kind regards,

Deon

**Comment by paullouisageneau** [comment]
Good catch, thanks for reporting. 

I think it's a regression from when I rewrote the URL parsing. Your fix goes around it but will result in the HTTP host missing the port number.

The actual mistake happens later as `mHost` is passed to `TlsTransport` instead of `mHostname`:
https://github.com/paullouisageneau/libdatachannel/blob/de47fec19bbc4d965fdc9933c7dfd7db7079bb80/src/websocket.cpp#L259

I'll push a fix.
