### ISSUE TITLE
Sending H.264 and Opus to browser

### ISSUE THREAD

**Issue by LeoNavel** [paullouisageneau/libdatachannel#242]
Hi Paul,

We would like to stream video and audio from our server to browser clients using WebRTC. The browser would use the JavaScript WebRTC API and would be receive only (no video/audio would be sent to the server). On the server, we get H.264 NAL units and Opus samples from a stream source in real time and we would like to use your library to stream them to the connected clients.

Is your library a good choice?

If so, how much do you think needs to be implemented to accomplish our goal with your library? Is there anything that should first be added to the library itself to make all this possible?

Could you provide any example where the server streams to the browser if your library supports streaming H.264 and Opus samples?

We will probably need to use the C API, because our backend is Swift, which cannot directly call into C++. However, if any part of the API is C++ only, we’re ready to write our own wrappers.

**Comment by stazio** [comment]
Hello Leo,
I am working on #176. That PR, as of now, is able to send audio and video to and from the browser. It can respond to RTP sender reports. It is close to being merged at this point. That said, there is no functionality in that PR to respond to NACK packets (the recovery strategy implemented by RTP), so loss on the line will make it unusable, but the library is capable of doing so, it just needs to be implemented. 
The last thing that I want to do before merging the PR is identify why I am causing segfaults inside of Safari/WebKit. But I think it is me misusing libdatachannel rather than it being a fault of libdatachannel itself.
There is an `sfu-media` example that shows how to send audio and video from browser to browser. That example will get you started. I would most likely recommend that you use a library like gstreamer to generate the RTP headers and perform clocking before forwarding that to the browser, otherwise you will need to synchronize the audio and video stream yourself, which is outside of the scope of this library, and not an easy task.

**Comment by paullouisageneau** [comment]
Hi Filip,

> Is your library a good choice?

If on the server side you have what's necessary to packetize audio and video data from your stream source as RTP, I think you are good, otherwise you can still make it work but you'll need to handle the RTP packetization yourself.

> If so, how much do you think needs to be implemented to accomplish our goal with your library? Is there anything that should first be added to the library itself to make all this possible?

Streaming from the browser to libdatachannel already works in master (that's what the `media` example does), but as @stazio mentionned to send from libdatachannel to the browser you need https://github.com/paullouisageneau/libdatachannel/pull/176 which will be merged very soon.

> We will probably need to use the C API, because our backend is Swift, which cannot directly call into C++. However, if any part of the API is C++ only, we’re ready to write our own wrappers.

The [sfu-media example in #176](https://github.com/stazio/libdatachannel/blob/api_updates/examples/sfu-media/main.cpp) is C++ however the C API already features track handling so you shouldn't need write wrappers: [include/rtc/rtc.h#L159](https://github.com/paullouisageneau/libdatachannel/blob/master/include/rtc/rtc.h#L159)

I'm currently documenting the C API, it's not finished but you can find the full draft here: [DOC.md](https://github.com/paullouisageneau/libdatachannel/blob/doc/DOC.md)

**Comment by paullouisageneau** [comment]
@LeoNavel FYI #176 has been merged.

**Comment by LeoNavel** [comment]
Great :) Thanks.

**Comment by LeoNavel** [comment]
I am trying to create example for [streaming H264 samples](https://github.com/in2core/libdatachannel/tree/feature/stream-h264) to browser. I am getting error `SRTCP protect error, status=13` (file: dtlssrtptransport.cpp, line: 134). Project is able to stream video when I removed lines 133 and 134 (as I did on mentioned branch). 

Do you have any idea how to fix this without removing `if ((err = srtp_protect_rtcp(mSrtpOut, message->data(), &size)))...`  ?

**Comment by paullouisageneau** [comment]
Status 13 from libsrtp means no appropriate context has been found. However, the SSRC should actually have been added just before by `addSSRC`. What media SDP do you use?

@stazio Is this an issue you encountered during tests?

**Comment by stazio** [comment]
@LeoNavel I just looked over that code and there seems to be a typo. Can you try with #273?

**Comment by LeoNavel** [comment]
Fixed, thanks 👍

**Comment by stazio** [comment]
That said, @LeoNavel, you should use `Description::Media::addSSRC`, especially if you are writing an example. Browsers can differentiate between payload types, but it is recommended to use SSRCs as payload types are reused between mlines.

**Comment by LeoNavel** [comment]
I call [addSSRC](https://github.com/in2core/libdatachannel/blob/c4a3023658e6f58b4b8d8b605629167d138cede4/examples/stream-h264/main.cpp#L230) in createPeerConnection. Should I call it somewhere else?

**Comment by stazio** [comment]
It seems you're not calling `PeerConnection::setLocalDescription()`. This is how you generate an offer that goes back to the browser via the `onDescription` callback, and how the SSRCs is added to the SRTP context. I believe you can call it immediately after you set the remote description but I could be wrong.

**Comment by LeoNavel** [comment]
@paullouisageneau May I add H264/opus -> rtp packetization to libdatachannel? I think it would be great to integrate this right into your library so others can benefit from it.

**Comment by paullouisageneau** [comment]
@LeoNavel Sure! Please try to keep it modular (like `RtcpHandler` for instance), and I'd like it to be guarded by `RTC_ENABLE_MEDIA`.

**Comment by LeoNavel** [comment]
What kind of guard do you want? Add `RTC_ENABLE_MEDIA` at the beggining and the end of  files with structures for h264 and opus streaming or just add `RTC_ENABLE_MEDIA` in some methods with `PLOG_WARNING`?

**Comment by paullouisageneau** [comment]
@LeoNavel Good question, if you managed to make in modular, `RTC_ENABLE_MEDIA` at the beginning of files would be nice!

**Comment by LeoNavel** [comment]
H264 and Opus streaming is implemented in #291 and all tests passed. :)
