### ISSUE TITLE
Question on how to set id and password of a turn server through C API

### ISSUE THREAD

**Issue by hanseuljun** [paullouisageneau/libdatachannel#275]
Seemingly, it is possible to provide STUN and TURN servers through rtcCreatePeerConnection in the C API by setting
const char **iceServers;
of struct rtcConfiguration.

The instances of the struct goes to IceServer::IceServer(const string &url) implemented in src/configuration.cpp. While I really think your usage of regex at the constructor of IceServer is a clever, as a regex newbie, it is hard for me to understand the following regex:
(^(([^:.@/?#]+):)?(/{0,2}((([^:@]*)(:([^@]*))?)@)?(([^:/?#]*)(:([^/?#]*))?))?([^?#]*)(\?([^#]*))?(#(.*))?)
Naively, I copy-pasted the regex to some websites (e.g., https://regexr.com/) but received errror messages and could not figure out what it stands for. 

Would it be possible to provide me (and some other potential users) an example (or add comment) of how to provide the ICE servers through the C API?

It would be great if there is an example of which string for "const char **iceServers" corresponds to the following TURN server:
url: example.com
id:  paul-louis
password: ageneau

Also, I would further appreciate it if you can let me know why you have modified a regex coming from a RFC on URI. I am just really curious whether the usage of regex for such servers is a common practice.

**Comment by paullouisageneau** [comment]
The format is similar to an HTTP URL: `turn:login:password@server.org:port`, so in your example it is "turn:paul-louis:ageneau@example.com"

The regex needed some modification from the RFC because an ICE server URI is kind of a degenerate version of the generic URI, as you need to specify a hostname and it doesn't need to be prefixed by "//". Also, the RFC regex doesn't match login and password so I added it.

I'm not a fan of regexes in general as they are hard to read, but for this kind of cumbersome multi-token parsing with optional components it's shorter than doing it manually.

I'll definitely add the format in the API documentation.

**Comment by hanseuljun** [comment]
Thanks a lot for the explanation!!

**Comment by hanseuljun** [comment]
This worked so I am closing it. Thanks!
