### ISSUE TITLE
Adding header files to libraries and executables

### ISSUE THREAD

**Issue by hanseuljun** [paullouisageneau/libdatachannel#311]
Currently, when using IDEs (like Visual Studio), header files don't appear on places like Solution Explorer.
![image](https://user-images.githubusercontent.com/5001447/105551719-d65b2480-5cb7-11eb-806a-b9d794405fd4.png)

Would you mind (of course I will do it if you just say yes) adding the header files to "add_library"s and "add_executable"s like below? That would let IDEs know where the header files are.
add_library(datachannel SHARED ${LIBDATACHANNEL_SOURCES} ${LIBDATACHANNEL_HEADERS})

I am totally sure you are a text editor person (README recommending nmake for Windows 😂) but it would be helpful for people like me!

**Comment by paullouisageneau** [comment]
> I am totally sure you are a text editor person (README recommending nmake for Windows joy) but it would be helpful for people like me!

ha ha indeed I'm not, I am more a vim on Linux person!

I'm OK for adding the private headers to `add_library`, however there is a catch: private headers (the ones in `src`) must be kept in a different variable than the actual library headers (the public ones in `include`) because the private ones must not be passed to `install` here:

https://github.com/paullouisageneau/libdatachannel/blob/329b133383cc2cd28ddf4d65afb0260901078d7a/CMakeLists.txt#L267
