### ISSUE TITLE
TURN credentials invalid with format of `username:hash:password` 

### ISSUE THREAD

**Issue by lukepolo** [paullouisageneau/libdatachannel#340]
I am using [coturn](https://github.com/coturn/coturn) , and the format is 

```
{
   username: "1613774196:someUser@gmail.com",
   credential: "XChjpcy9z9vf0NPKnqJbs8KTR+4=" // base 64 hash
}
````

Using it would require me to send it like 

`turn:1613774196:someUser@gmail.com:XChjpcy9z9vf0NPKnqJbs8KTR+4=@coturn.my.network`

This seems to return 401, is there something I can to make it work with this library?

**Comment by paullouisageneau** [comment]
The issue is that the URI `turn:1613774196:someUser@gmail.com:XChjpcy9z9vf0NPKnqJbs8KTR+4=@coturn.my.network` will be parsed as user `1613774196` with password `someUser@gmail.com:XChjpcy9z9vf0NPKnqJbs8KTR+4=`.

The reason is the username must not contain a colon when using HTTP-style credentials in URI, as stated in [RFC 2617]'https://tools.ietf.org/html/rfc2617#section-2): `userid = *<TEXT excluding ":">`.

You may instead create the ICE server entry with the explicit constructor: `IceServer("coturn.my.network", 3478, "1613774196:someUser@gmail.com", "XChjpcy9z9vf0NPKnqJbs8KTR+4=");`
