### ISSUE TITLE
problems with different MTU's

### ISSUE THREAD

**Issue by dshurbin** [paullouisageneau/libdatachannel#345]
Good day.
Actually, it is obvious if a server has MTU = 1500 and a client has MTU = 1300 the client's interface will drop most of packets exceeding MTU. 
But, is there a way to limit MTU somehow in the library, because it is not always possible to change it for a client?

**Comment by murat-dogan** [comment]
Hi,
Because of a bug in usrsctp MTU path discovery is disabled in code.
Please check here;
https://github.com/paullouisageneau/libdatachannel/blob/c37c88543d5a48310d1f6729683eb372993f0f46/src/sctptransport.cpp#L34

And MTU is fixed at 1200. 
https://github.com/paullouisageneau/libdatachannel/blob/c37c88543d5a48310d1f6729683eb372993f0f46/src/sctptransport.cpp#L188

You should not see a MTU value of 1500 I think.

Am I right @paullouisageneau ?

**Comment by dshurbin** [comment]
Hi,
> You should not see a MTU value of 1500 I think.
for now the situation is like this: server has MTU=1500; clients with MTU=1500 are getting good picture. those clients who has MTU=1300 are seeing nothing and multiple frames dropped in the stats

**Comment by paullouisageneau** [comment]
Indeed, @murat-dogan is right, path MTU discovery has been disabled for DataChannels from libdatachannel v0.11 since it is not implemented properly in usrsctp leading to this kind of problems. The MTU is hardcoded to 1200, which is a safe value recommended by the RFC in case discovery is not possible.

@dshurbin Is it possible you are not using the last version?

**Comment by dshurbin** [comment]
> @dshurbin Is it possible you are not using the last version?

well, I cloned it last time 1-st Feb 2021. At the newer version changed RtcpSenderReporter name and some things regarding initialization. Not yet updated my code. But the line mentioned by @murat-dogan  is present in my version

**Comment by dshurbin** [comment]
There is one thing that could be importaint - this client MTU is related to openVPN tun interface. 1300 - this is overall unit size and packet may contain extended header

**Comment by paullouisageneau** [comment]
Note the line `spp.spp_pathmtu = 1200` will be present in any case, the important part is the comment at the beginning followed by the unconditional `#define USE_PMTUD 0`.

> There is one thing that could be importaint - this client MTU is related to openVPN tun interface. 1300 - this is overall unit size and packet may contain extended header

OK interesting, there might be a way that it exceed 1300 in the end. Actually, the SCTP MTU should be lower than 1200 for IPv4 because it should account for DTLS/UDP. I'll run some tests.

**Comment by paullouisageneau** [comment]
The issue should be fixed by https://github.com/paullouisageneau/libdatachannel/pull/346

**Comment by dshurbin** [comment]
> The issue should be fixed by #346

is it possible to add possibility to limit MTU via library mechanisms? Sure I can do it myself, but it will not be compatible with future setups, getting library from GIT. Just to add small function to setup the limit, mm?

**Comment by paullouisageneau** [comment]
Sure, I don't think path MTU discovery will be available soon in usrsctp so I added an optional `mtu` setting in `rtc::Configuration`.

**Comment by dshurbin** [comment]
Thanks a lot!
