### ISSUE TITLE
Example client.exe create datachannel will get stuck nearby  DTLS handshake.

### ISSUE THREAD

**Issue by Arronjeck** [paullouisageneau/libdatachannel#375]
**[Environment]**
PC1: 192.168.1.3 （Client1）
PC2: 192.168.2.241 （Client2）
Signaling: 192.168.1.3

**[Steps]**
1. client1 execute and connect signaling success.
2. client2 execute and connect signaling success.
3. client2 input client1`s ID.
4. Then check connecting state.

**[AS-IS]**
Datachannel open fail.
![data channel create fail](https://user-images.githubusercontent.com/7685902/111898721-ba2ef600-8a62-11eb-9dd5-364edaafd860.png)

**[TO-BE]**
Datachannel open success.

**[Addition]**
If client1 and client2 in the same PC, The datachannel will open success.

**Comment by paullouisageneau** [comment]
It's actually not stuck, ICE has failed because it did not find a working bidirectional path, that's why the DTLS handshake doesn't happen. The client does not close as it waits on input for another remote ID.

Given your two client addresses `192.168.1.3` and `192.168.2.241`, I guess you have two cascading NATs: the first router masquerades 192.168.1.0/24 behind a public address and the second router is seen as a client by the first router and masquerades 192.168.2.0/24 behind its client address 192.168.1.X (One would expect the second router routing the 192.168.2./24 prefix without masquerading it).

For ICE to be able to open a direct connection between hosts on the two subnets in such a pathological topology, you can't use a public STUN server, you need the STUN server to be located between the two NATs. For instance, you could deploy it on `192.168.1.3`, the same host as the signaling server.

**Comment by Arronjeck** [comment]
@paullouisageneau 
Maybe I understood it, You mean DTLS need to be used in the same domain?
And if I try to use in two cascading NATs or two clients on the Internet.
It will not support it, right?

**Comment by paullouisageneau** [comment]
It's actually unrelated to DTLS. To sum up, to be able to open a P2P connection between the subnets of two cascading NATs, the STUN server itself must be in the first subnet.
