### ISSUE TITLE
question about a negation of an unsigned integer

### ISSUE THREAD

**Issue by hanseuljun** [paullouisageneau/libdatachannel#380]
The below line negates an unsigned integer and assigns it back to itself. First, I don't know what happens when an unsigned integer is negated, don't know the intention behind this line of code, so couldn't remove this by myself. Second, MSVC for UWP considers this (negation of an unsigned integer) as an error.

https://github.com/paullouisageneau/libdatachannel/blob/460fe747671b8f531c1ae1c3eaa6b8aa3b276f79/examples/streamer/fileparser.cpp#L31

**Comment by paullouisageneau** [comment]
When an unsigned integer goes in the negative range, it actually wraps into the higher values, so basically `uint64_t(-N)` is equal to `uint64_t(2^64 - N)`. Here, it's only done so that the first time `sampleTime_us` is incremented by `sampleDuration_us` in `loadNextSample`, it equals zero. 

Does changing the line to `sampleTime_us = uint64_t(-sampleDuration_us)` fixes the error?

@LeoNavel As you have written this example, please feel free to correct if I'm missing something.

**Comment by LeoNavel** [comment]
@paullouisageneau You are correct.

**Comment by hanseuljun** [comment]
Thanks for your quick responses! I'll try it soon!

**Comment by hanseuljun** [comment]
Oh, now I see that it was assigning to a different variable, not the same one!

Casting to uint64_t did not work but, based on your explanation, below line would be equivalent, so I submitted a corresponding PR!
sampleTime_us = std::numeric_limits<uint64_t>::max() - sampleDuration_us + 1;

**Comment by paullouisageneau** [comment]
Thanks for the fix!
