### ISSUE TITLE
Feature request: expose performance-related usrsctp options in API

### ISSUE THREAD

**Issue by ptesavol** [paullouisageneau/libdatachannel#394]
As we are currently trying to optimise the throughput of libdatachannel/node-datachannel here at Streamr,  it would help a lot if the performance-related  usrsctp options were exposed in the APIs of libdatachannel/node-datachannel. These options include (but are not limited to):

```
usrsctp_sysctl_set_sctp_sendspace()
usrsctp_sysctl_set_sctp_recvspace()
usrsctp_sysctl_set_sctp_max_chunks_on_queue()
usrsctp_sysctl_set_sctp_default_cc_module() 
usrsctp_sysctl_set_sctp_initial_cwnd()
```

Maybe a setSctpOptions(SctpOptions & options) function or similar could be added, where SctpOptions would be an associative array of options (that would nicely map into a Javascript Object in node-datachannel).

Would this kind of enhancement be possible?

**Comment by paullouisageneau** [comment]
> Maybe a setSctpOptions(SctpOptions & options) function or similar could be added, where SctpOptions would be an associative array of options (that would nicely map into a Javascript Object in node-datachannel).
>
> Would this kind of enhancement be possible?

Sure, such a global function could be added. Note that due to how usrsctp works, most changes will be reflected only on newly-created `PeerConnection` instances. Is that limitation OK for you?

Also I think changing `sctp_sendspace` and `sctp_recvspace` wouldn't have any effect since the buffer sizes are set dynamically on each `PeerConnection`.

**Comment by ptesavol** [comment]
The limitation to newly-created PeerConnections is no problem.

**Comment by murat-dogan** [comment]
@ptesavol Did you find a better config?

I guess libdatachannel has already optimized config.

Isn't it @paullouisageneau ?

**Comment by ptesavol** [comment]
We have developed a benchmarking tool for node-datachannel which we will release shortly. Our plan is to try out different configs on the benchmarking tool to find an optimal config.

**Comment by ptesavol** [comment]
@murat-dogan @paullouisageneau We just released the node-datachannel benchmarking tool for node-datachannel at https://github.com/streamr-dev/node-datachannel-performance-diagnostics/tree/main/benchmark and also opened an issue for it at the [node-datachannel repo](https://github.com/murat-dogan/node-datachannel/issues/34). 

Hope it is helpful in optimising libdatachannel/node-datachannel!

**Comment by paullouisageneau** [comment]
@murat-dogan It's kind of optimized, but there is a lot of room for enhancement, especially since new versions of usrsctp might introduce big performance changes, like we have seen with the congestion control.

@ptesavol Thanks, I'll have a look! The option setter shouldn't take too long to add.

**Comment by hanseuljun** [comment]
Can I just add a question here? I have tried streaming video using an unreliable and unordered datachannel, but it did not work so ended up using media transports. The issue was with congestion control, which I am not sure why it is needed for an unreliable and unordered case.

The whole reason I tried this datachannel approach for video was because Zoom is currently using datachannel for their web client (https://webrtchacks.com/zoom-avoids-using-webrtc/), and it works well. Can optimization of usrsctp potentially make video streaming happen through a datachannel as Zoom does?

**Comment by murat-dogan** [comment]
@paullouisageneau if you are not started to write it I can give a hand.

**Comment by paullouisageneau** [comment]
@murat-dogan Thanks, but I'm nearly finished. I'll let you do the JavaScript binding, if you please.

**Comment by paullouisageneau** [comment]
`rtcSetSctpSettings()` is now available in the C API:
https://github.com/paullouisageneau/libdatachannel/blob/436d77eab79beb0e54bb7e0488405100078bab14/include/rtc/rtc.h#L234

More settings can be added later if needed.

**Comment by murat-dogan** [comment]
I ported the feature to `node-datachannel` v0.1.2.

**Comment by paullouisageneau** [comment]
@murat-dogan Thanks!
