### ISSUE TITLE
Any plan to support FEC ?

### ISSUE THREAD

**Issue by reischen80** [paullouisageneau/libdatachannel#395]
Hi, paullouisageneau, 

SCTP seems not to support FEC(forward error coding), which is not friendly to scenario with tiny, high-frequence and low-latancy data transmission , such as remote gaming control,   In this case, retransmission is unacceptable due to the latency of  2-3 times rtt.  And usually FEC is most effecient tool.

Since SCTAP can transfer ordered data, with attaching a sequence num to the message. Then there might be some way to extend SCTP with FEC supported.  

Any plan for that? If not, any suggested QOS config (now available) for the scenario I mentioned above.

**Comment by hanseuljun** [comment]
I am not paullouisageneau and I do not know much about including FEC inside a webrtc library, but as a person currently using this library with FEC, I just wanted to recommend you to check out https://github.com/catid/wirehair in case you are looking for a nice FEC library (to be strict it is a fountain code but quite similar in what it does). catid has some other similar libraries too!

**Comment by paullouisageneau** [comment]
While it could make sense in theory, there are no plans to support FEC as there is no interoperable standard to implement FEC in SCTP (just like there is none for TCP).

As suggested by @hanseuljun, you can however get decent results by adding a FEC on top of SCTP (a fountain code to generate batches works, but inserting a XOR FEC message every few messages is computationally way lighter). To do so, you need to open an unreliable and unordered Data Channel and send FEC-encoded messages with your own sequence numbers through it. There are two caveats: you must refrain from sending if `bufferedAmount()` is not zero, otherwise delay will increase, and you should send messages roughly as large as the MTU, e.g. 1200 bytes, otherwise SCTP might bundle multiple messages per packet.

As a side note, FEC might be added to QUIC (possibly as a [Random Linear Code](https://tools.ietf.org/html/draft-roca-nwcrg-rlc-fec-scheme-for-quic-03)), which means it could be available in the upcoming [RTCQUICTransport](https://w3c.github.io/webrtc-quic/).

**Comment by reischen80** [comment]
The FEC message as large as the MTU  would introduce extra bandwidth usage and congestion, especially in my case, gaming control(tiny data with extra-low latency).  USRSCTP has an option of usrsctp_sysctl_set_sctp_max_burst_default() to limit the packet num in one flight。Is that more efficient?

**Comment by paullouisageneau** [comment]
If you send tiny messages with some interval between them like gaming control, you might be good. Nagle's algorithm in SCTP is disabled, meaning it will only bundle multiple chunks if you send faster than it can send the data.

`usrsctp_sysctl_set_sctp_max_burst_default()` actually controls the maximum number of packets sent in a row, not the number of data chunks bundled per packet.
