### ISSUE TITLE
Question on streaming video over an unrealiable & unordered datachannel

### ISSUE THREAD

**Issue by hanseuljun** [paullouisageneau/libdatachannel#396]
Reading #394, I have a question. I have tried streaming video using an unreliable and unordered datachannel, but it did not work so ended up using media transports. The issue was with congestion control, which I am not sure why it is needed for an unreliable and unordered case (why is congestion control happening when there is no expectation)?

The whole reason I tried this datachannel approach for video was because Zoom is currently using datachannel for their web client (https://webrtchacks.com/zoom-avoids-using-webrtc/), and it works well. Can optimization of usrsctp potentially make video streaming happen through a datachannel as Zoom does? Sorry to ask a question not directly about code, but I would really appreciate an answer.

**Comment by paullouisageneau** [comment]
That's actually a good question. Actually, flow control and congestion control have nothing to do with reliability, you can have one without the other. The goal of flow control is to prevent sending faster than the receiver can handle, the goal of congestion control is to prevent sending faster than the network path can handle.

SCTP Data Channels, just like TCP, send as fast as possible. Therefore, there must be a way to limit the sending rate, even when the data is unreliable. Otherwise, sending any file, even unreliably, would result in a immediate burst of data at the fastest rate your computer can achieve and overflowing packets would be massively dropped on the network path. So not only you would lose most of it, but other streams on the network would be disrupted too. 

Media transport has no congestion control because it assumes the source sends at a pre-defined average bitrate. The bitrate is assumed to be achievable, and often there is RTCP feedback so the encoder can adapt its target bitrate if there are too many losses.

Streaming over Data Channels feels a bit like a hack but it should work kind of OK, provided that you use a bitrate low enough compared to the available network capacity and that you drop messages instead of sending them when `bufferedAmount` is not zero. Maybe it's related, there has been a recent fix on usrsctp settings, I think there was a regression at some point with the alternate congestion control which prevented SCTP from reaching a good throughput (see https://github.com/paullouisageneau/libdatachannel/pull/361).

**Comment by hanseuljun** [comment]
Thanks for your kind and thorough explanation! I originally even thought using a datachannel for streaming as some simpler, therefore better, but you feeling like a hack (i.e., your insight haha) means a lot to me. So the rationale of having congestion control in SCTP is similar to TCP! I will be trying the datachannel approach again since I am working on streaming things that are not video color pixels,  so your information about the congestion algorithm helps a lot too! Thanks a ton!!
