### ISSUE TITLE
Specific ipv4 address in libjuice not works

### ISSUE THREAD

**Issue by reischen80** [paullouisageneau/libdatachannel#421]
@paullouisageneau 
In my case, there is three network adapters with three diffrenet local IP, and one of them needed to be specified for datachannel.

I tried to customize the  hostname param to getaddrinfo()  when udp_create_socket(), like as:
`getaddrinfo("30.211.115.154", "0", &hints, &ai_list) != 0)`
Then I got "Failed to interrupt thread by triggering socket, errno=10049" at agent_interrupt(). 
Any tips for that?

Addtionally, I simply modify 
`if ((ai = find_family(ai_list, AF_INET6)) == NULL &&  (ai = find_family(ai_list, AF_INET)) == NULL) {`
to 
`if ((ai = find_family(ai_list, AF_INET)) == NULL &&  (ai = find_family(ai_list, AF_INET6)) == NULL) {`

and won't work any more,  Got "STUN message send failed, errno=10047".
why ipv6 is prefered in query local address?

**Comment by paullouisageneau** [comment]
> I tried to customize the hostname param to getaddrinfo() when udp_create_socket(), like as:
> `getaddrinfo("30.211.115.154", "0", &hints, &ai_list) != 0)`
> Then I got "Failed to interrupt thread by triggering socket, errno=10049" at agent_interrupt().
> Any tips for that?

This is expected. libjuice needs to listen on any address, especially because it sends datagrams to itself through `localhost` (this is the only portable method to interrupt a call to `select()`).

> Addtionally, I simply modify
> `if ((ai = find_family(ai_list, AF_INET6)) == NULL && (ai = find_family(ai_list, AF_INET)) == NULL) {`
> to
> `if ((ai = find_family(ai_list, AF_INET)) == NULL && (ai = find_family(ai_list, AF_INET6)) == NULL) {`
> 
> and won't work any more, Got "STUN message send failed, errno=10047".
> why ipv6 is prefered in query local address?

IPv6 is preferred since IPv4 means IPv4-only and IPv6 means IPv6+IPv4 when disabling the option `IPV6_V6ONLY`, therefore one must pick IPv6 if supported to use both.

It should still work when picking IPv4-only, however there was a problem with IPv4-only on Windows and MacOS I fixed some time ago. Do you have the last version of libjuice with the fix (https://github.com/paullouisageneau/libjuice/pull/92)? You should only need to update the submodule on the last libdatachannel version.

> In my case, there is three network adapters with three diffrenet local IP, and one of them needed to be specified for datachannel.

If libjuice doesn't generate a candidate for one of your interfaces, the issue is not related to the interface it listens too, but possibly to the way adapters are enumerated: https://github.com/paullouisageneau/libjuice/blob/43933459d493a033ffa4b3bdc36a58a8741e9d72/src/udp.c#L359

**Comment by reischen80** [comment]
Thanks for the infomation. I will check out the updated Libjuice. 

Actually, the specified adapter can be listerned to correctly and able to receive stun request message from remote endpoint(cellphone behind Wifi router) , and then it sends back the stun response message to the Reflex Candidate(from the stun request messge).  But the cellphone  cannot receive the stun response message.  I think it may be stuck by the Wifi router because the udp message seems not to be traceable and treated as a flood attack. That is reason I tried to specified the local IP at getaddessinfo(). (Actually, I have tried bind() the Local ip directly and not work either)

Do you have any suggestion for the reason the cellphone can not receive the stun response message?

**Comment by paullouisageneau** [comment]
The STUN response should appear to the router as an answer to the STUN request. As such, it should be allowed through the firewall and translated back into the private address range by the NAT. What is your exact test scenario? Are both your endpoints behind different Wifi routers? What access technology do they use (fiber, cable, 4G/LTE, etc)?

> That is reason I tried to specified the local IP at getaddessinfo(). (Actually, I have tried bind() the Local ip directly and not work either)

This won't work as you have to listen on either an address of an interface of the local machine or any address (libjuice needs to listen on any address). You can't listen on the public address of your router, it's a different device.

**Comment by reischen80** [comment]
One of endpoints is a cloud server in public domain (Peer A) with three network adapters and the other is a cellphone behind Wifi router (Peer B).  They are reachable to each other in some other udp based application. And surely there is a way to connect them.

For some reason, Only one of the three public addresses in Peer A is available and all the them can be listened to.

Since libjuice needs to listen on any address, to my knowledge, it means the socket is not binded to any local address.  So Peer A can receive STUN Request , while sending udp message through this socket, things becomes ambiguous.  We cannot garuntee the message is sent by the exact address we want to use,  and may be ignored by the other two adapter or by the Wifi Router 
at Peer B.  That is why I tried to bind a specific address in Peer A to make it 'valid'. 

I notice that the latest libjuice has a new iterm in udp socket allowing the socket binded to a customize local address, as:

`if (getaddrinfo(config->bind_address, "0", &hints, &ai_list) != 0)`

But it is ignored in agent.c  Is this feature still on the road?

**Comment by paullouisageneau** [comment]
> One of endpoints is a cloud server in public domain (Peer A) with three network adapters and the other is a cellphone behind Wifi router (Peer B). They are reachable to each other in some other udp based application. And surely there is a way to connect them.
> 
> For some reason, Only one of the three public addresses in Peer A is available and all the them can be listened to.
> 
> Since libjuice needs to listen on any address, to my knowledge, it means the socket is not binded to any local address. So Peer A can receive STUN Request , while sending udp message through this socket, things becomes ambiguous. We cannot garuntee the message is sent by the exact address we want to use, and may be ignored by the other two adapter or by the Wifi Router
> at Peer B. That is why I tried to bind a specific address in Peer A to make it 'valid'.

Your understanding is correct, however nothing should be ambiguous. Like every node, Peer A has a routing table with at least a route to a default gateway to reach nodes outside of the local network. The route also specifies which interface should be used to reach the default gateway. The default interface will be used for outgoing traffic unless stated otherwise.

This means when Peer B reaches Peer A on a non-default interface, it will see the response coming from the default interface, so either the Wifi router drops the message (since it can't go through the firewall or NAT), or Peer B gets it and drops it (because the ICE protocol mandates to fail candidates if the response comes from another address).

However, when Peer B reaches Peer A on its default interface, the response will come as expected from the remote interface. Therefore, the Wifi router should accept it (it's no different from the response of any UDP server) and the candidate will be selected as the valid one.

If that doesn't work, there might be a weird network configuration involved. Could you please send me the verbose log if you want me to have a look?

> I notice that the latest libjuice has a new iterm in udp socket allowing the socket binded to a customize local address, as:
> 
> `if (getaddrinfo(config->bind_address, "0", &hints, &ai_list) != 0)`
> 
> But it is ignored in agent.c Is this feature still on the road?

It is only used by the new STUN/TURN server (in `server.c`).

**Comment by reischen80** [comment]
Thanks. @paullouisageneau 
It works  after binding the address to the socket and specifing the same address to interrupt select(). 
As you said, the Peer B happens to negotiate with the default interface (of three) at Peer A.

**Comment by paullouisageneau** [comment]
I exposed the bind address setting from libdatachannel in https://github.com/paullouisageneau/libdatachannel/pull/425, as it can indeed be useful for multi-homed servers.
