### ISSUE TITLE
use of undeclared identifier 'plog'

### ISSUE THREAD

**Issue by jeffRTC** [paullouisageneau/libdatachannel#438]
I made the upgrade into your newest version and successfully built the library but when compiling my program, the compiler Clang emit these errors,

```
In file included from /usr/local/include/rtc/rtc.hpp:24:
/usr/local/include/rtc/global.hpp:43:32: error: use of undeclared identifier 'plog'
RTC_CPP_EXPORT void InitLogger(plog::Severity severity, plog::IAppender *appender = nullptr);
                               ^
/usr/local/include/rtc/global.hpp:43:57: error: use of undeclared identifier 'plog'
RTC_CPP_EXPORT void InitLogger(plog::Severity severity, plog::IAppender *appender = nullptr);
```

**Comment by paullouisageneau** [comment]
The error means `PLOG` is defined but the `plog` namespace is not, meaning `PLOG` is defined in your code before the inclusion without the plog library being actually included.

If you don't need the plog version of `InitLogger`, just remove references to plog before including `rtc/rtc.hpp`. Otherwise, import plog properly by including `plog/Log.h` before `rtc/rtc.hpp`.

**Comment by jeffRTC** [comment]
@paullouisageneau No, I don't use Plog. It's from your library.

**Comment by jeffRTC** [comment]
@paullouisageneau 

I was able to compile by including plog before rtc header but I don't use plog. 

So, is this a bug in your new version?

This was never the case with your previous version. I bet there are breaking changes you have made...

**Comment by paullouisageneau** [comment]
Please be cordial and a show a minimum of humbleness. If it's a bug in the current version, it affects only your setup for some reason.

The issue happens because `PLOG` is defined in your program when `rtc/rtc.hpp` is included. It shouldn't be defined if you don't use plog. Why is it defined?

**Comment by paullouisageneau** [comment]
Please be cordial and a show a minimum of humbleness. If it's a bug in the current version, it affects only your setup for some reason.

The issue happens because the `PLOG` macro is defined in your code before `rtc/rtc.hpp` is included. It shouldn't be defined if you don't use plog. Why is it defined?

**Comment by jeffRTC** [comment]
@paullouisageneau  I have checked, can't find any macro definitions.

**Comment by paullouisageneau** [comment]
It has to be defined somewhere, the code in `rtc.hpp` is guarded by a `#ifdef PLOG`.

**Comment by jeffRTC** [comment]
I bet this one caused the breakage in new version,

https://github.com/paullouisageneau/libdatachannel/pull/404

**Comment by paullouisageneau** [comment]
> I have separate library which uses Google's glog and defines PLOG
> 
> How about renaming your PLOG to DC_PLOG?

The point is to detect plog to expose the function for retro-compatibility, renaming to something custom like `DC_PLOG` or `RTC_PLOG` would break it for people still using the plog appender.

I think checking for `PLOG_DEFAULT_INSTANCE_ID` instead should prevent name collisions with other libs.

> I bet this one caused the breakage in new version,
> 
> #404

In your case it was kind of broken before as two incompatible libraries were attempting to define the same macro.
