### ISSUE TITLE
Unable to handle PLI as sender

### ISSUE THREAD

**Issue by kuzux** [paullouisageneau/libdatachannel#543]
Hello there again. Curently, when we create a video track on a webrtc connection, and we can get a video stream rendering on google chrome. The problem is; the stream freezes after a couple of minutes. During these freezes, the pliCount in webrtc-internals constantly increases. Such freezes do not occur if we send keyframes periodically (by specifying a small, non-infinite gop length to the h264 encoder). So, we're assuming that these hapen becasuse google chrome can't continue rendering the video without getting a new intra frame, and then it sends a picture loss indicator to the sender via webrtc. Sender then does not handle the PLI message, and just continues sending new frames. During all this time, nackCount in webrtc internals stays at zero.

I can also see a line like `a=rtcp-fb:123 nack pli` in the webrtc offer created by the sender. So, my first question is: "How do we handle a pli message?". Is it supported by libdatachannel? Because if we can just handle pli messages, we can force the encoder to emit a keyframe and send that. Additionally, for nack; there is an `RtcpNackResponder` in the library and we add that to chain (as in the samples), so I'm assuming nack messages would be handled if they were emitted by the browser, and that would, hopefully, lead to a better streaming experience. So, the question is simply: "How do we get the browser to send nack messages?"

**Comment by paullouisageneau** [comment]
Hello, 

You analysis seems correct, however is there a reason why you don't send intra-frames periodically? It's way more robust as with an infinite GOP length, errors due to packet loss add up and can't be corrected automatically, eventually causing such situations. I don't think you should rely on PLI or NACK as anything else than mitigations.

If I'm I'm not mistaken, for now PLI is implemented for libdatachannel as receiver but not as sender. The issue is that implementing it as sender would require a custom channel to inform the encoder somehow.

I think the issue comes from the fact libdatachannel advertises PLI while it won't answer PLI as a sender. You could try commenting out the `nack pli` RTCP-FB in the advertised media description so the browser falls back to NACK instead: 

https://github.com/paullouisageneau/libdatachannel/blob/0975afa07d3bf804fa04b217bf8ad559ed4edb1c/src/description.cpp#L876

**Comment by kuzux** [comment]
Handling PLI was eventually solved by writing a custom handler (subclassing a MediaHandlerElement) for PLI messages (pretty easy, ~20 lines of code). After handling PLI messages, the stream is more resilient to connection issues but it's still not perfect (as you've said before). So we're still planning to send keyframes periodically, just less frequent.

About the custom PLI handler, I might integrate the handler into the main libdatachannel codebase (it's currently inside the caller code) create a PR for that after.

**Comment by paullouisageneau** [comment]
Excellent, your contribution would be very welcome!
