### ISSUE TITLE
OpenSSL write failure

### ISSUE THREAD

**Issue by murat-dogan** [paullouisageneau/libdatachannel#56]
I am using iPerf3 to test speed.
But I am getting an error from this line https://github.com/paullouisageneau/libdatachannel/blob/6e647e64b1fd8f8f15859a80dbc96a31233dd25b/src/dtlstransport.cpp#L441

Error:
```
error:00000005:lib(0):func(0):DH lib
```

**Comment by murat-dogan** [comment]
If I comment this line everything still works. 
https://github.com/paullouisageneau/libdatachannel/blob/6e647e64b1fd8f8f15859a80dbc96a31233dd25b/src/dtlstransport.cpp#L324 

I could not find a way to catch the error from outside

**Comment by paullouisageneau** [comment]
This could be OpenSSL reporting a protocol error because the write fails at some point under heavy constrain.
Since with DTLS dropped packets are safe to ignore, you could try replacing this line: https://github.com/paullouisageneau/libdatachannel/blob/6e647e64b1fd8f8f15859a80dbc96a31233dd25b/src/dtlstransport.cpp#L572
by
```
transport->outgoing(make_message(b, b + inl));
return inl;
```
Let me know if that solves the problem.

**Comment by murat-dogan** [comment]
Yes it solved the problem.
Could you please create a pull request for this?

**Comment by paullouisageneau** [comment]
Sure, I'll do it. Thanks for reporting that issue!
