### ISSUE TITLE
libjuice forces relay in two ways，Have a better suggestion？

### ISSUE THREAD

**Issue by LiuAriel** [paullouisageneau/libdatachannel#575]
There are two ways to force relay in the libjuice library:
1. Remove the host and srflx types of candidate when parsing SDP,
2. When doing pair in agent_add_candidate_pairs_for_remote, judge that the type of remote is equal to relay.
Have a better suggestion, looking forward to a reply?
3. If there is a problem with the turn address, or the network is not good, gathering is blocked. It is because turn is doing allocata. According to the description of the rfc document, the time for each retry is a multiple of 2. Although this is true, it is too long to wait for done. It is recommended to add an interface to enable faster mode to increase a value of Accurate, the whole process of p2p itself takes a very short time to complete.
4. The time to do this has been reduced from the original waiting time of 30s to 4s, and I added a status callback to indicate that the turn server connection failed, the relay is different, and the problem can be located faster, in the case of different networks.

**Comment by paullouisageneau** [comment]
You should ask questions about libjuice on the libjuice repository instead of the libdatachannel one.

The proper way is indeed to filter out the non-relay candidates (host and server reflexive). While this can be achieved on the full SDP, it is easier when trickling candidates, i.e. getting them in gradually from the candidate callback. Note libdatachannel has a build-in candidate filter allowing to force relaying with `TransportPolicy::Relay`.

If you wait for gathering to finish in order to send the full SDP description. An issue with a TURN server will indeed introduce a delay and gathering will take longer. The solution to this is to use ICE candidate trickling rather than sending the full SDP through signaling. The process is as follows:
- Get the local description from `juice_get_local_description` and send it
- Start candidates gathering with `juice_gather_candidates`
- Get candidates gradually through the `cb_candidate` callback and send them
- If you don't get a relay candidate soon enough (after 4s for instance), you can assume a TURN server issue

This does not require to tweak the library and make it non-compliant with the ICE standard.

**Comment by LiuAriel** [comment]
1. OK, next time I will mention the corresponding place;
2. Forced turn, thank you very much for your answer;
2. It is indeed a way to use trickle mode for time-consuming problems, but since all peers are in full mode, it cannot be solved very well. Since the result is not clear whether it can be p2p or relay, I hope to get the reasons described above. Turn is in some In this case, if the connection fails, the reason can be obtained in the project, which is convenient to eliminate the reason, and can also understand the reason why the project is done according to the standard. This also has some functions customized.

**Comment by paullouisageneau** [comment]
I'm closing this, please reopen an issue on the libjuice repository if needed.
