### ISSUE TITLE
Unable to play audio stream in browser.

### ISSUE THREAD

**Issue by ulo1230** [paullouisageneau/libdatachannel#589]
I am trying to stream audio from libdatachannel to a Javascript client with the client as the offerer and libdatachannel the answerer.
The client creates a receive only audio track and libdatachannel receives it with `onTrack`.
```
// client creates audio track
let audio = pc.addTransceiver("audio", { direction: "recvonly" });
document.querySelector("audio").srcObject = new MediaStream([audio.receiver.track]);
```
```
peerConnection->onTrack([this](std::shared_ptr<rtc::Track> track) {
	AddAudio(track);
});
```
In `AddAudio` the track is initialized. I tried to make it similar to the `addAudio` function in <https://github.com/paullouisageneau/libdatachannel/blob/master/examples/streamer/main.cpp#L239>
```
void Client::AddAudio(std::shared_ptr<rtc::Track> track)
{
	const std::string trackId = track->description().mid();
	const std::string streamId = "stream1";
	const uint8_t payloadType = 111;
	const uint32_t ssrc = 1;

	rtc::Description::Audio description(trackId, rtc::Description::Direction::SendOnly);
	description.addOpusCodec(payloadType);
	description.addSSRC(ssrc, trackId, streamId, trackId);

	auto rtpConfig = std::make_shared<rtc::RtpPacketizationConfig>(ssrc, trackId, payloadType, rtc::OpusRtpPacketizer::defaultClockRate);
	auto packetizer = std::make_shared<rtc::OpusRtpPacketizer>(rtpConfig);
	auto opusHandler = std::make_shared<rtc::OpusPacketizationHandler>(packetizer);

	auto srReporter = std::make_shared<rtc::RtcpSrReporter>(rtpConfig);
	opusHandler->addToChain(srReporter);

	auto nackResponder = std::make_shared<rtc::RtcpNackResponder>();
	opusHandler->addToChain(nackResponder);

	track->setDescription(description);
	track->setMediaHandler(opusHandler);
	audio = std::make_unique<TrackData>(track, srReporter, false);

	track->onOpen([srReporter]() {
		std::cout << "audio open" << std::endl;
		double time = std::chrono::duration_cast<std::chrono::nanoseconds>(std::chrono::system_clock::now().time_since_epoch()).count() / 1000000000.0;
		srReporter->rtpConfig->setStartTime(time, rtc::RtpPacketizationConfig::EpochStart::T1970);
		srReporter->startRecording();
	});
}
```

It seems like the packets are successfully sent from libdatachannel to the Javascript client in the browser as chrome://webrtc-internals shows that data is being received but the Audio object does not to play the stream.

I tried the client in chrome then firefox but neither worked, then rewrote the client in nodejs using the node-webrtc addon. Unlike browsers, samples were being received and everything worked fine. Is there a problem with how I initialize the audio track in libdatachannel that causes the stream to not play in the browers?

**Comment by paullouisageneau** [comment]
There are multiple potential issues here:

- You are trying to change the description of the track in the answer SDP. To do this, you need to switch to manual negotiation `disableAutoNegotiation` in the PeerConnection configuration and call `setLocalDescription()` after you modify the track description. Otherwise, `onTrack` is called asynchronously and your modifications might not be taken into account.

- The browser offered to receive the track, so it already decided on the payload type it wants to receive in the offered track description, while you send audio with the hardcoded payload type 111, therefore the browser discards the packets. Here, you should get and modify the browser's track description rather than blindly replacing it, possibly with something incompatible.

Offering to receive from the browser is rather tricky and I'd advise against it. It's way easier to offer the desired track description from libdatachannel and let the browser answer.

**Comment by paullouisageneau** [comment]
There are multiple potential issues:

- You are trying to change the description of the track in the answer SDP. To do this, you need to switch to manual negotiation `disableAutoNegotiation` in the PeerConnection configuration and call `setLocalDescription()` after you modify the track description. Otherwise, `onTrack` is called asynchronously and your modifications might not be taken into account.

- The browser offered to receive the track, so it already decided on the payload type it wants to receive in the offered track description, while you send audio with the hardcoded payload type 111, therefore the browser discards the packets. Here, you should get and modify the browser's track description rather than blindly replacing it, possibly with something incompatible.

Offering to receive from the browser is rather tricky and I'd advise against it. It's way easier to offer the desired track description from libdatachannel and let the browser answer.

**Comment by ulo1230** [comment]
I think that there is likely to be a different problem, as I have now added a couple of asserts to check if either of these things occur and they seem to pass. I will probably end up making libdatachannel the offerer instead, but I would like to see if it possible to get the reverse working first. Thanks for the quick response!

```
void Client::AddAudio(std::shared_ptr<rtc::Track> track)
{
	const std::string streamId = "stream1";
	const uint8_t payloadType = 111;
	const uint32_t ssrc = 1;

	auto description = track->description();

	assert(description.hasPayloadType(payloadType));
	description.addSSRC(ssrc, description.mid(), streamId, description.mid());

	// unchanged code
	...

	assert(!peerConnection->localDescription().has_value());
}
```

**Comment by ulo1230** [comment]
Having the libdatachannel as the offerer works a lot better and I can't figure out how to have it as the answerer. Thanks for your help.

**Comment by paullouisageneau** [comment]
> I think that there is likely to be a different problem as I have now added some asserts to check if either of these things occur and they seem to pass. I will probably end up making libdatachannel the offerer instead, but I would like to see if it possible to get the reverse working first. Thanks for the quick response!
> 
> ```
> void Client::AddAudio(std::shared_ptr<rtc::Track> track)
> {
> 	const std::string streamId = "stream1";
> 	const uint8_t payloadType = 111;
> 	const uint32_t ssrc = 1;
> 
> 	auto description = track->description();
> 
> 	assert(description.hasPayloadType(payloadType));
> 	auto* rtpMap = description.rtpMap(payloadType);
> 	assert(rtpMap->format == "opus");
> 
> 	description.addSSRC(ssrc, description.mid(), streamId, description.mid());
> 
> 	// unchanged code
> 	...
> 
> 	assert(!peerConnection->localDescription().has_value());
> }
> ```

The assert on `localDescription` might not be sufficient here to ensure the track information is taken into account, as without `disableAutoNegotiation` and a manual call to `setLocalDescription()` the processing of the local description runs in parallel with the `onTrack` callback, creating a race condition (the other thread might have read the track info already but still not set the local description). The only way to know if the changes were picked up or not would be to look at the SDP answer.

> Having the libdatachannel as the offerer works a lot better and I can't figure out how to have it as the answerer. Thanks for your help.

OK great!
