### ISSUE TITLE
juice: Changing state to failed

### ISSUE THREAD

**Issue by kylegranger** [paullouisageneau/libdatachannel#633]
Salut!  I'm having a problem sending audio packets, and I'm not sure what I've done incorrectly.

The scenario most simply stated it this:  I am using libdatachannel in a C++ client running on Android.  It connects to an SFU server built with the library running on Linux.  The client is sending (and receiving) Opus RTP packets.  It uses the RTC WebSocket.  No DataChannel is used.  At the moment, the server uses the uWebSocket library for signalling.

Everything has been working nicely, most of the time.  PeerConnections get instantiantiated, the gathering state reaches the completed state, clients can talk and hear each other.  

I've found though, when I moved the server from localhost to an external server, the client sometimes stops sending out on its track after a few minutes:  track->send() returns false.  After turning on verbose logging, I see the PeerConnection has been set to a failed state because juice has been set to a failed state.  From the log, that's the earliest thing wrong that I've seen.
```
rtc::impl::IceTransport::LogCallback@354: juice: Changing state to failed
```
Just 10 seconds before, I do see this in the log:  `juice: STUN server binding successful`, so I don't yet see a smoking gun as to why juice fails.

BTW, the client never stops receiving packets from the server.  The user can always hear the other users in the group, so it's not a networking issue.

I've tried various lists of iceServers, but it typical uses at least these:
```
config.iceServers.emplace_back("stun:stun.stunprotocol.org:3478");
config.iceServers.emplace_back("stun:stun.l.google.com:19302");
```
I'm probably missing something in my setup or ice/offer/answer message handling, but I don't yet have a clue what that might be.

Thank you for any suggestions.

addendum:  
The library code used in client is commit 075917e, 8 April 2022, 'Pages: undated reference'
The server is using commit 0975afa, 18 January 2022

**Comment by paullouisageneau** [comment]
Thank you for reporting. It looks like the ICE failure timeout triggers because pair nomination never succeeded, even if communication has been established. I would need the whole verbose log to be sure.

Does the issue still exist with the last libdatachannel version with libjuice v1.0.0? libjuice v0.9.x implements aggressive nomination which was removed in v1.0.0 accordingly to the last RFC, so the related code changed a bit.

**Comment by kylegranger** [comment]
Hi Paul, thanks for the response!
Sure, I will try with the latest code -- I admit now, I could have updated both server and the client libraries first.
I'll let you know how it goes.

**Comment by kylegranger** [comment]
I've updated both client and server to the latest code.  Unfortunately, the juice fail is still happening.
The list of ice servers I'm currently using is the same as above:
```
config.iceServers.emplace_back("stun:stun.stunprotocol.org:3478");
config.iceServers.emplace_back("stun:stun.l.google.com:19302");
```
I use the same list on server, when creating a PeerConnection to talk to the client.

As before, I do hear what the client is transmitting right up until the PeerConnection is put into a failed state.

Attached is a verbose log.



[juice-fail.log](https://github.com/paullouisageneau/libdatachannel/files/8729164/juice-fail.log)

**Comment by kylegranger** [comment]
One other question...should I even be setting the ice servers in a PeerConnection in the server?  The server has its own IP address (and SSL certificates).  But I found when I didn't set them, a connection would never complete.

**Comment by paullouisageneau** [comment]
Thanks for the log. It's quite hard to read as it seems to mix multiple runs, timestamps go back and forth sometimes (for instance `14:34:17.691` followed by `14:32:21.399`), and it doesn't indicate the log level. `ICE role conflict` is actually a warning and indicates something could be incorrect with signaling.

It's indeed an ICE nomination problem, but for now it's not obvious to me what could cause this. The signaling shows an offer sent to the remote peer with the mid `audio-stream`, then an offer received from the remote peer with another mid, then an answer sent to the remote peer (It causes the `ICE role conflict` warning since both peers assume they are the offerer). This looks wrong. You should instead offer the track on side and accept it on the other.

> Should I even be setting the ice servers in a PeerConnection in the server? The server has its own IP address (and SSL certificates). But I found when I didn't set them, a connection would never complete.

Indeed, you don't need a STUN server in that case if the server machine has a public IP address. However, if there is a NAT on the way as it is the case here (the server machine has the private IP address 172.31.21.2), you need to either forward the port range and manually translate the IP address of local host candidates to the public address, or use a STUN server to traverse the NAT automatically.

**Comment by kylegranger** [comment]
Merci encore une fois...
1) I apologize for the timestamps -- for some reason, that's how they got captured in logcat.  Weird.
2) Regarding STUN on the server, understood, thanks.
3) The ICE role conflict is obviously the source of my misery.  Thanks for the heads-up.  I know where to look now.

I think the root of my problem is the track creation.  I think I might be creating too many?

E.g., a scenario with 3 users all talking together.  User A has ssrc 1001, B had 1002, and C has 1003.  The way it's currently set up, the server sends all offers.   4 tracks are created per user:

for User A:  
   track 1: created on server, following initial connection and creation of peer connection. At the moment it's SendRecv, but it only receives packets from the client. ssrc is 1001.
   track 2:  created on the client to send audio (also SendRecv, but it only sends).  ssrc also is 1001.
   track 3:  When A joins user B, the server creates a (transmit) track with ssrc 1001 on the B's peer connection.  Client A's audio gets sent on this track out to B when incoming audio.  A new local description is gotten from B's peer connection, and a new offer is sent.  This is possibly where my problem is.
   track 4:  When C joins A & B,  the server creates a track with ssrc 1001 on the C's peer connection, and an offer is sent to C.  Client A's audio now gets sent to both B & C (which also do the same thing, sending their audio to A).

questions
1) Should I be able to combine 1 & 2?  The client peer gets a ontrack event (with track 1 from the server), and then, since it is full duplex, set move the client RTP code currently done on the new track 2 to this track 1:
```
    auto track = mPeerConnection->addTrack(audio);  //don't add track, rather use received track in peer->ontrack()
    auto rtpConfig = make_shared<RtpPacketizationConfig>(mSsrc, cname, payloadType, OpusRtpPacketizer::defaultClockRate);
    auto packetizer = make_shared<OpusRtpPacketizer>(rtpConfig);
    auto opusHandler = make_shared<OpusPacketizationHandler>(packetizer);
    auto srReporter = make_shared<RtcpSrReporter>(rtpConfig);
    opusHandler->addToChain(srReporter);
    auto nackResponder = make_shared<RtcpNackResponder>();
    opusHandler->addToChain(nackResponder);
    track->setMediaHandler(opusHandler);
    track->onOpen(onOpen);  // this is track 2; if track 1, skip because already open
```
2)  Am I stuck creating a track for every pair in a group of users, mesh-like?  N*(N-1) tracks.  Or is there a way to send packets with different ssrcs on one track?  The ssrc is in the RTP header, which I use for the user key -- all audio processing is done outside of WebRTC.

Thank you for looking at the log file.

**Comment by paullouisageneau** [comment]
> I think the root of my problem is the track creation. I think I might be creating too many?

In fact, this setup triggers a bug: adding an additional track on the fly before the ICE connection has completed might result in libjuice being unable to finish the connection process properly. It should be fixed by https://github.com/paullouisageneau/libjuice/pull/157.

> E.g., a scenario with 3 users all talking together. User A has ssrc 1001, B had 1002, and C has 1003. The way it's currently set up, the server sends all offers. 4 tracks are created per user:
>
> for User A:
> track 1: created on server, following initial connection and creation of peer connection. At the moment it's SendRecv, but it only receives packets from the client. ssrc is 1001.
> track 2: created on the client to send audio (also SendRecv, but it only sends). ssrc also is 1001.
> track 3: When A joins user B, the server creates a (transmit) track with ssrc 1001 on the B's peer connection. Client A's audio gets sent on this track out to B when incoming audio. A new local description is gotten from B's peer connection, and a new offer is sent. This is possibly where my problem is.
> track 4: When C joins A & B, the server creates a track with ssrc 1001 on the C's peer connection, and an offer is sent to C. > Client A's audio now gets sent to both B & C (which also do the same thing, sending their audio to A).

This could work as a design even if it doesn't scale, however track 1 and track 2 result in both the server and client offering the peer connection at the same time, resulting in an offer collision.

> Should I be able to combine 1 & 2? The client peer gets a ontrack event (with track 1 from the server), and then, since it is full duplex, set move the client RTP code currently done on the new track 2 to this track 1

Yes, this is way better. Note you still have to wait for `onOpen()` for a track received in `onTrack()`. Contrary to data channels, tracks are received when setting the remote description and opened later on connection.

> Am I stuck creating a track for every pair in a group of users, mesh-like? N*(N-1) tracks. Or is there a way to send packets with different ssrcs on one track? The ssrc is in the RTP header, which I use for the user key -- all audio processing is done outside of WebRTC.

A more efficient approach would be using only one bidirectional track for each user, and have the server decode, mix, reencode, then broadcast mixed audio to everybody, like an MCU (Multipoint Conferencing Unit) would do.

**Comment by kylegranger** [comment]
Paul, thank you for your detailed comments.  It clears up a lot of things for me.
I will close the issue for now.
Of course, I will update it when I get everything running correctly.
