### ISSUE TITLE
Using ffmpeg in examples/media-sender

### ISSUE THREAD

**Issue by swdmnd** [paullouisageneau/libdatachannel#644]
Hi, I tested using gstreamer to stream my webcam but it shows blank video, so I use ffmpeg instead. Now I want to use libdatachannel to make the stream available over webrtc, so I take a look at the example and try to create a stream similar to the recommended gstreamer command:

```
ffmpeg -f video4linux2 -i /dev/video0 -preset ultrafast -vcodec libx264 -tune zerolatency -b:v 1k -f rtp -payload_type 96 rtp://127.0.0.1:6000?pkt_size=1200
```

and after some time the example would output:

```
INFO  [1357] [rtc::impl::IceTransport::LogCallback@354] juice: conn_poll.c:422: Send failed, buffer is full
```

is it the wrong ffmeg command?

**Comment by swdmnd** [comment]
In my earlier test this warning would show up, but it doesn't anymore.

```
WARN  [901] [rtc::impl::IceTransport::LogCallback@354] juice: conn_poll.c:424: Send failed, errno=90
```

**Comment by paullouisageneau** [comment]
> ```
> ffmpeg -f video4linux2 -i /dev/video0 -preset ultrafast -vcodec libx264 -tune zerolatency -b:v 1k -f rtp -payload_type 96 rtp://127.0.0.1:6000?pkt_size=1200
> ```

The ffmpeg command looks good, but 1 Kbit/s is way too low. You should try `-b:v 1000K` instead (gstreamer implicitely requires Kbit/s for bitrate, I guess that's where the error comes from). You should also add `-pix_fmt yuv420p -profile baseline` to set the h264 profile to constrained baseline.

> and after some time the example would output:
> 
> ```
> INFO  [1357] [rtc::impl::IceTransport::LogCallback@354] juice: conn_poll.c:422: Send failed, buffer is full
> ```

This typically happens when the RTP bitrate is too high compared to what the network interface can actually send. If you get only a burst of them once it's no big deal, but if you keep getting them it indicates an actual issue.

> In my earlier test this warning would show up, but it doesn't anymore.
> 
> ```
> WARN  [901] [rtc::impl::IceTransport::LogCallback@354] juice: conn_poll.c:424: Send failed, errno=90
> ```

Errno 90 is `EMSGSIZE`, meaning the message is too big. You should be fine with `pkt_size=1200`.

**Comment by swdmnd** [comment]
Thank you for your reply! As suggested, I get it working with

```
ffmpeg -re -f video4linux2 -i /dev/video0 -preset ultrafast -vcodec libx264 -pix_fmt yuv420p -profile:v baseline -tune zerolatency -b:v 1000k -f rtp -payload_type 96 rtp://127.0.0.1:6000?pkt_size=1200
```

Thank you again for your time!

**Comment by swdmnd** [comment]
Sorry, just a quick question, if the ffmpeg restarted, the output from the example would be:

```
Error: SRTP protect error, status=10
```

Where is this come from? Is there a way to handle this without having to lose all connections to connected clients?

**Comment by paullouisageneau** [comment]
The issue is that you can't just replace a stream with another. Since RTP streams are sequenced and timestamped, restarting ffmpeg breaks the continuity. Here, the sequence number restarting lower instead of increasing prevents SRTP encoding here. 

I think there is no easy solution. While you could fix the symptom by resequencing packets in the forwarding loop, playback will still be broken or delayed because the timestamps do not match, therefore you would also need to offset timestamps somehow each time the incoming SSRC changes.

Proper ways to handle such restarts would require either changing approaches and renegotiating a track when a new SSRC comes in instead of blindly replacing the SSRC, or going for a more advanced design with packetization inside of libdatachannel like in the streamer example.

**Comment by swdmnd** [comment]
I'll take a look at streamer and renegotiation. Thank you!
