### ISSUE TITLE
Channel::send: set custom dscp field value

### ISSUE THREAD

**Issue by alexswerner** [paullouisageneau/libdatachannel#657]
Is there a way to set custom dscp value for Media/Datachannel packets?

**Comment by paullouisageneau** [comment]
No, there is no way to set a custom DSCP, the library always set the values recommended for WebRTC. I don't think letting the user set custom DSCP values is a good idea.

For Data Channels, it assumes medium priority. If a user setting for priority control is implemented in the future, it wouldn't be per-message due to how SCTP works, it would have to be per-DataChannel like in the [WebRTC Priority Control API](https://www.w3.org/TR/webrtc-priority/).

**Comment by alexswerner** [comment]
Agree, having per packet tunning ability is unnecessary. The priority control API looks useful. In the application here, this would be useful as after multiplexing everything on one UDP port, there is no way a traffic shaper can differentiation between the different applications. After correctly understanding the default values for video/auto/datachannels I can work with the current implementation. Feel free to close this.
