### ISSUE TITLE
Clarification on setting local description with setLocalDescription()

### ISSUE THREAD

**Issue by rajukasaramoni** [paullouisageneau/libdatachannel#658]
Hello Paul-Louis,

I have referred to peerconnection.hpp APIs and example programs like copy-paste. In this we do not have way to send the negotiated offer description as local description with setLocalDescription () sort of API. This setLocalDescription () does not take any input and it sets the description decided by the libdatachannel internally (some fields are hardcoded like sctp port). how to set the application decided (through negotiation with SIP) description like SCTP port, UDP port, fingerprint etc. Can you please help answering this.

(sorry I am resubmitting here as I have wrongly asked on libjuice earlier)

**Comment by paullouisageneau** [comment]
As the name indicates, the local description is generated locally and when obtained via `onLocalDescription` must be sent to the remote peer which sets it with `setRemoteDescription()`. Conversely, the description received from the remote peer must be set with `setRemoteDescription()`. 

You should not need to set a custom description in `setLocalDescription()` as it reflects local parameters. For instance since the fingerprint must be the one of the certificate the library has generated, it wouldn't make sense to specify another. Negotiation happens automatically as the remote description is taken into account (The answer is adapted if the remote description is an offer).

Note the call to `setLocalDescription()` is actually optional by default: if `disableAutoNegotiation` is `false` in the configuration, both `createDataChannel()` and `setRemoteDescription()` internally call `setLocalDescription()`.

**Comment by rajukasaramoni** [comment]
Thanks for clarification.
