### ISSUE TITLE
Have an option to install either static or dynamic library

### ISSUE THREAD

**Issue by Marwan-imverse** [paullouisageneau/libdatachannel#685]
It would be great to have the option to install either the static or the dynamic library version.

Since there are two different CMake targets, it's already possible to build either one, but the install target automatically builds both, we have no choice.

**Comment by paullouisageneau** [comment]
The install target should only build and install the dynamic library, not the static ones. Are you sure it builds both for you?

**Comment by Marwan-imverse** [comment]
I misspoke at the end of my first comment. If I choose to "install" after I built the static library, it builds and installs the dynamic library, which is not what I'd like. The install target should either install the dynamic or the static library, depending on how the project was generated with CMake.

**Comment by paullouisageneau** [comment]
OK I see. I think a preliminary step for this would be to bundle the static libraries of submodules into the static library of libdatachannel.

**Comment by Marwan-imverse** [comment]
Great, thanks! I'll keep an eye on this

**Comment by ClayJay3** [comment]
@paullouisageneau I think this is still an issue, has any development been made? I'm currently able to build the static library just fine with `make datachannel-static`, but then running either `make install` or `make install datachannel-static` doesn't install the library statically, but instead dynamically.

I suppose I could manually copy everything needed for the static install, but I wanted to check if there's an 'official' way to do this.

**Comment by ClayJay3** [comment]
I got the library to statically install with 
```
cmake \
    -D USE_GNUTLS=0 -D USE_NICE=0 \
    -D BUILD_SHARED_LIBS=OFF \
    -D CMAKE_BUILD_TYPE=Release ..
```

Then, the normal `make install` will work.

**Comment by ClayJay3** [comment]
I checked out to `cmake-add-install-deps-export` and it seems to have fixed the issue with the `make install` command ignore that I want it to install the static libs, and I can go manually check `/usr/local/lib/libdatachannel.a` and it exists. however it seems like the install library is still broken :(

When I add the library to my project with find_package() like this:
![image](https://github.com/user-attachments/assets/3b28fd9a-52ac-497d-96ed-5f9b31d891d7)
![image](https://github.com/user-attachments/assets/563bd1cb-4829-4e82-b031-3352a9cefa84)
It gives me this:
![image](https://github.com/user-attachments/assets/8c219193-2cb0-4a5c-a2f3-22f0391e87de)
Switching the link library to `LibDataChannel` instead of `LibDataChannelStatic` seems to find the library (is LibDataChannelStatic still relavant?), but complains about OpenSSL for some reason:
![image](https://github.com/user-attachments/assets/adea8f8d-c664-4a84-8e83-1cdcfcc64605)


For reference, this is how I'm building and installing libdatachannel:
```
# Download LibDataChannel
    git clone --recurse-submodules --depth 1 --branch cmake-add-install-deps-export https://github.com/paullouisageneau/libdatachannel.git libdatachannel
    mkdir libdatachannel/build
    cd libdatachannel/build

    # Build LibDataChannel
    cmake \
    -D USE_GNUTLS=0 -D USE_NICE=0 \
    -D BUILD_SHARED_LIBS=OFF \
    -D CMAKE_BUILD_TYPE=Release ..

    # Install LibDataChannel
    make datachannel-static
    make install datachannel-static
```

**Comment by ClayJay3** [comment]
Forgot to mention that trying

```
## Find LibDataChannel
find_package(LibDataChannel-Static REQUIRED)
```
Does not find anything either.

**Comment by paullouisageneau** [comment]
The change introduced in https://github.com/paullouisageneau/libdatachannel/pull/1274 makes the `LibDataChannel` default target obey the CMake flag `BUILD_SHARED_LIBS`, so you can now build it statically and install it.

The `LibDataChannelStatic` target is still not installable, because CMake doesn't support optionally installing a configured target. Don't try to install it.

You simply have to run:
```
$ mkdir libdatachannel/build
$ cd libdatachannel/build
$ cmake -D USE_GNUTLS=0 -D BUILD_SHARED_LIBS=OFF -D CMAKE_BUILD_TYPE=Release ..
$ make
$ make install
```

Then you can import it with:
```
find_package(OpenSSL REQUIRED)
find_package(LibDataChannel REQUIRED)
[...]
target_link_libraries(${EXE_NAME} PRIVATE LibDataChannel::LibDataChannel)
```
You have to provide the same OpenSSL version as during the build since static libraries are linked only when linking the executable.

**Comment by ClayJay3** [comment]
#1287 seems to have fixed my issue with the static build. I think this issue can be closed once that PR is merged.
