### ISSUE TITLE
Message size limit for libdatachannel library

### ISSUE THREAD

**Issue by fuqifacai** [paullouisageneau/libdatachannel#702]
I remember offical webrtc library has message size limit on DataChannel .Such as 256Kib on Chrome , 1GiB on FireFox.
So my question is this library has the same issue or ?
Thanks /

**Comment by paullouisageneau** [comment]
Data channels have a message size limit in libdatachannel too, however you can easily increase it with the configuration setting `maxMessageSize` (default 256 KiB) on both sides.

Note that when connected with a browser, you are still limited by the browser limit (typically 256KiB or 1MiB). Also, sending very large messages should be avoided due to the memory footprint, if you need more than a few MiB you should consider streaming the data over many messages.

**Comment by fuqifacai** [comment]
Thanks for the reply ,very helpful.
