### ISSUE TITLE
onGatheringStateChange

### ISSUE THREAD

**Issue by oops-code** [paullouisageneau/libdatachannel#717]
Hello, during my use, the response time of the `pc->onGatheringStateChange` function suddenly became very long. It originally only took a few seconds, but now it takes 30 seconds. What is the reason?

**Comment by paullouisageneau** [comment]
The reason is very probably that one of the STUN/TURN servers did not answer. Since the gathering process is only finished when all candidates have been gathered, it has to wait for a timeout for that server after a few retransmissions.

I guess you use the test server `stun.ageneau.net`. It is currently down because outrageously careless people put it in large-scale production and it couldn't handle the traffic. You should use another server, ideally your own.

**Comment by oops-code** [comment]
Another question, there are only four `ice-candidates` collected each time in the demo. What should I do if I want to get more? Add more usable stun servers?

**Comment by paullouisageneau** [comment]
> Another question, there are only four `ice-candidates` collected each time in the demo. What should I do if I want to get more? Add more usable stun servers?

Candidates are only a reflection of your network setup. There will be one host candidate for each interface, one server reflexive candidate if there is a NAT, and one relay candidate per TURN server. ICE with libjuice will currently only use two TURN servers at once as more is not useful. In practice, having more candidates does not correlate with better connectivity, but it might cause the ICE connection checks to take longer.

**Comment by paullouisageneau** [comment]
I'm closing this as the issue seems solved.
