### ISSUE TITLE
Freezing frame on current master

### ISSUE THREAD

**Issue by kuzux** [paullouisageneau/libdatachannel#740]
This is actually a continuation of #732, but a separate problem. While trying to enable twcc, we needed to use features in PR #678. To do that, we created a new branch locally and merged the PR branch and master in that. And then added the twcc lines in SDP and using a media handler on the peer connection. After doing that, the connection started freezing after a second, but resumed later (and then froze again).

Looking at webrtc internals, it looked like sender was continously sending data, but the receiver was not considering the received data as new frames (suggesting a depacketization issue to me)
<img width="1378" alt="Screen Shot 2022-11-08 at 12 23 08" src="https://user-images.githubusercontent.com/20781/201677087-05f9336c-cea5-4652-bfd0-0aac356d5303.png">

Changing the packetization mode in sdp did not help.

Then, to isolate the problem; we removed the interceptor logic, removed the twcc lines from sdp, and the error still persisted. Then; we tried with a master build of libdatachannel (from commit 648f7172770f9e56cf4bed7900c04efe1bb754bb), and the problem still continues

**Comment by paullouisageneau** [comment]
Thank you for reporting. From the symptoms, it really looks like a missing keyframe issue: Too many packets are lost, causing entire frames to be lost, as a result the decoder is unable to continue decoding and has to send PLIs and wait for the next properly-received keyframe to resume playback. 

As you can see, the `packetLost` count is abnormally high, it looks like nearly 3% packets are consistently lost. This could be caused by a queue or buffer overflowing or a packetization issue (like packets too large or incorrect sequence numbers). What is your setup? Do you use libdatachannel for packetization? Is this a local test or does it transmit across an actual network?

**Comment by kuzux** [comment]
* We use libdatachannel for packetization (passing H264 frames cominfg from the encoder straight to it)
* This transmits over an actual network (remote side is running on a cloud instance)

**Comment by paullouisageneau** [comment]
For now I fail to see a relevant change on master. The only thing that changed is the return value of `Track::send` that was fixed to return false when the UDP buffer overflows. Do you check it in some way?

**Comment by kuzux** [comment]
For some reason, updating to commit `c97ae665368540825db4375b981d3f3216d61d04` seemed to solve the problem. Do you have any idea why this might be the case? 

By the way, while debugging the problem, i noticed that the lastReceivedTimestamp is about 33 hours off from the timestamp value (which is the correct time). This does not cause a playback problem, but we're just curious why that is the case
<img width="652" alt="Screen Shot 2022-11-24 at 15 47 46" src="https://user-images.githubusercontent.com/20781/203788708-c05f85d7-1e33-471a-83cd-eb54247de26a.png">
<img width="687" alt="Screen Shot 2022-11-24 at 15 47 56" src="https://user-images.githubusercontent.com/20781/203788714-c00d3262-d81d-4e85-8a55-86f0b0d30da9.png">

**Comment by paullouisageneau** [comment]
This is surprising, but still that's good news. I've no idea what solved it, the fix https://github.com/paullouisageneau/libdatachannel/pull/752 could have helped, but the issue was present in 0.17 too.

Here `timestamp` corresponds to the stats object creation time (the JavaScript stats API is misleading) and is not related to the RTP flow. `lastPacketReceivedTimestamp` should be the arrival time of the last RTP packet, so very close to present time. That's weird but if playback I wouldn't think too much about it.
