### ISSUE TITLE
WebSocket stuck in Connecting state (TLS/OpenSSL)

### ISSUE THREAD

**Issue by aleksey-salow** [paullouisageneau/libdatachannel#869]
**How to reproduce**: Start a WebSocket server with TLS enabled (built with OpenSSL). Try to establish a connection from a browser using a non-secure `ws://` socket.
**Observed behavior**: Socket stuck in Connecting state
**Expected behavior**: Socket closed, onError or onClosed event handlers is called.

A quick look under the debugger shows that `SSL_do_handshake` returns `-1`, which is correct and indicates an error according to the OpenSSL documentation.
https://github.com/paullouisageneau/libdatachannel/blob/c0f4203c02d5746cbaaaab4fd6f5b90431def38d/src/impl/tlstransport.cpp#L707-L709

But `openssl::check` compares the return value with `BIO_EOF` and returns `true`. And looks like this check should be removed, because the negative return value indicates an error in OpenSSL. But this function is called from multiple places, and I'm not sure there will be no side effects.
https://github.com/paullouisageneau/libdatachannel/blob/c0f4203c02d5746cbaaaab4fd6f5b90431def38d/src/impl/tls.cpp#L178-L180

**Comment by paullouisageneau** [comment]
Indeed, I think the is a confusion because reading will effectively return `BIO_EOF` when there is no more data in the input memory BIO, as it is set by `BIO_set_mem_eof_return(mInBio, BIO_EOF)`, however the return value should not be checked against it here. The empty input BIO situation should be properly handled by the `err == SSL_ERROR_WANT_READ` just after.

**Comment by paullouisageneau** [comment]
Fixed by #875
