### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by aleksey-salow** [paullouisageneau/libdatachannel#882]
How to reproduce: run the 'media-sender' example, connect from the browser, stream some video, and wait a while.

All incoming messages are stored in the track's receive queue for further processing (`Track::incoming()` method), which is unexpected for `SendOnly` streams. Since there is no message handler registered on the track, the message queue will continue to grow until the track is not destroyed. Possibly, some logic should be added to store messages only for `RecvOnly` or `SendRecv` tracks or not to store `Control` messages (like was done in the `datachannel.cpp`)

https://github.com/paullouisageneau/libdatachannel/blob/3fd1b1a2ac24a4a95f6a063ea8be518b7b01f9fa/src/impl/track.cpp#L145

**Comment by paullouisageneau** [comment]
There should not be a memory leak here because the queue as a maximum size of ` RECV_QUEUE_LIMIT` (1 MiB) and will drop packets after that if they are not read by the user:
https://github.com/paullouisageneau/libdatachannel/blob/5edb3bbbda118c97e6812e72db02c43386976219/src/impl/internals.hpp#L44
https://github.com/paullouisageneau/libdatachannel/blob/3fd1b1a2ac24a4a95f6a063ea8be518b7b01f9fa/src/impl/track.cpp#L140

Contrary to control packets in data channels, which are for internal in-band signaling, control messages for tracks are actually RTCP packets that the user may want to read. The callback could however be set to a dummy function by default for `SendOnly` tracks to discard everything if the user does not set a callback.

**Comment by paullouisageneau** [comment]
There is actually an issue with `mRecvQueue` in `Track` as it relies on `message_size_func` which does not take `Control` messages into account to compute the size. I'll push a fix for this.
