### ISSUE TITLE
DTLS Handshake seems to fail when connecting Android/Linux

### ISSUE THREAD

**Issue by X-Kent** [paullouisageneau/libdatachannel#98]
Hello.

I am using libdatachannel when two peers are running on different OSes.
Peer1 Linux 64 bit (ubuntu 18.04)
Peer2 Android 10

The problems seems only to happen when android is "answering" and Linux is "offering".
Two peers are in fact in local network but do get a working stun server on the internet when creating connection.
I see that they in fact can successfully talk to each other but for whatever reason DTLS handshake seems to fail.

when android is "offering" and Linux is  "answering" everything works fine.
when android is "answering" and Linux is "offering" I never got to connection success. It seems the DTLS handshake doesn't receive anything although there is data received as I can see from the logs.
STUN does seem to succeed too.
On Android I use the same openssl(compiled by me) as on Linux.
Linux <-> Linux communication always works.
Android <-> Android communication does not seem to work at all.

I have prepared log files of the sessions (mostly coming from libjuice) + annotation of what I do but as they are a bit long I don't think posting here is appropriate. 
Logs are available at https://gofile.io/d/v3lXb9

Zip contains two directories with two files in each directory.
dir "android_is_answerer_does_not_work" contains android.txt and linux.txt when DTLS seems to get stuck.
dir "android_is_offerer_does_work" contains android.txt and linux.txt when it does work.

I am using libdatachannel from https://github.com/paullouisageneau/libdatachannel/tree/usrsctp-fix-notifications

Did anyone get anything like it ? The behavior seems to change due to offer/answer so I believe it libdatachannel related.

**Comment by paullouisageneau** [comment]
Thanks for the logs, looking at them it seems the DTLS handshake failure is not the root of the problem. It actually looks like Android does not receive what is sent by Linux after ICE is connected when it is the answerer (so when it is in the ICE controlled role), in particular it never receives the DTLS server hello. So my guess is this is probably an Android-specific issue with ICE.

I recently pushed some fixes in [libjuice](https://github.com/paullouisageneau/libjuice), and I just added error checking on send since it was missing. Could you please retry with the current master? (Don't forget to update the submodules) 

If it still doesn't work, the Android log might give us more information about the issue.

**Comment by X-Kent** [comment]
I used the https://github.com/paullouisageneau/libdatachannel/tree/usrsctp-fix-notifications branch. Is it already merged to master ? As without this fix, I get the problem of  len(messages)>65k...
I will update libjuice from it's own git master repo, rebuild and see if it fixes it.
If the problem still happens I will update to libdatachannel to master branch and check again.
I will report back my findings.

**Comment by paullouisageneau** [comment]
Don't worry, it's merged to master. Updating libjuice on its own should work too!

**Comment by X-Kent** [comment]
I updated libjuce from current master and it fixed the problem.
Linux to Android (when android is answering) is working.
Android to Android is working too.

This may be my build specific issue(I build libdatachannel/juice in my project build environment) but I will mention:
I have noticed that libjuice has a call to "getrandom" in random.c
getrandom() is not available on old androids (I target API 21) I believe it was added in API 28.
proper/safe random number generation is obviously out of scope of our debug/testing so I just replaced "static int random_bytes(void *buf, size_t size)" body with:
char *ptr = (char*)buf;    
for (int i = 0; i < size; ++i)
    ptr[i] = rand();
You may want to add some ifdef android there or something.

Thank you for your great work!
I find libjuice and libdatachannel to be very useful components. I have experience working with other ICE libraries(nice/pjnath etc) and this one seems to be the easiest to work with.
The part that you can libjuice instead of libnice is just fantastic (libnice is OK but it requires all the gobject/glib etc stuff which are just too big for small libraries/projects)
Having webrtc.datachannel capability without full WebRTC behemoth library is a great benefit.

**Comment by paullouisageneau** [comment]
Thanks for your very positive feedback, I'm glad the libraries are useful for you! The usage simplicity was indeed the main goal so it's cool to have achieved it in some extend. 

It's great it works now, I don't exactly know what the problem was on Android but that's for the better.

Rather than replacing `random_bytes()`, I think you could get away with changing `#if defined(__linux__)` to `#if defined(__linux__) && !defined(__ANDROID__)` here: 
https://github.com/paullouisageneau/libjuice/blob/7cd5e53d54f83048122e14a6cc52f6ac38b7a98c/src/random.c#L27
This will output a failing `random_bytes()` instead and `juice_random` will fallback on `random()` which should be available on Android.
